// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus1.Maintenance.Infrastructure.Persistence;

#nullable disable

namespace Nexus1.Maintenance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MaintenanceDbContext))]
    [Migration("20260817002208_InitialMaintenanceSchema")]
    partial class InitialMaintenanceSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus1.Maintenance.Domain.Asset", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AssetId");

                    b.Property<int>("AssetCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("AssetCategoryId");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("AssetCriticalityId")
                        .HasColumnType("int")
                        .HasColumnName("AssetCriticalityId");

                    b.Property<int>("AssetStatusId")
                        .HasColumnType("int")
                        .HasColumnName("AssetStatusId");

                    b.Property<DateTime?>("CommissionedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsSafetyRelated")
                        .HasColumnType("bit");

                    b.Property<string>("LocationText")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RetiredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("SystemId")
                        .HasColumnType("int")
                        .HasColumnName("SystemId");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_Asset");

                    b.HasIndex("AssetCategoryId");

                    b.HasIndex("AssetCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Maintenance_Asset_AssetCode");

                    b.HasIndex("AssetCriticalityId");

                    b.HasIndex("AssetStatusId");

                    b.HasIndex("UnitId");

                    b.ToTable("Asset", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.AssetCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AssetCategoryId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_AssetCategory");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Maintenance_AssetCategory_Code");

                    b.ToTable("AssetCategory", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.AssetComponent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AssetComponentId");

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("AssetId");

                    b.Property<string>("ComponentCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsReplaceable")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentAssetComponentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentAssetComponentId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_AssetComponent");

                    b.HasIndex("ParentAssetComponentId");

                    b.HasIndex("AssetId", "ComponentCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Maintenance_AssetComponent_Asset_ComponentCode");

                    b.ToTable("AssetComponent", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.AssetCondition", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("AssetConditionId");

                    b.Property<DateTime>("AssessedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("AssessedAtUtc");

                    b.Property<int?>("AssessedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("AssessedByUserId");

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("AssetId");

                    b.Property<string>("Basis")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Basis");

                    b.Property<int>("ConditionGradeId")
                        .HasColumnType("int")
                        .HasColumnName("ConditionGradeId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<decimal?>("HealthScorePercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("HealthScorePercent");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Notes");

                    b.Property<int?>("RemainingUsefulLifeDays")
                        .HasColumnType("int")
                        .HasColumnName("RemainingUsefulLifeDays");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_AssetCondition");

                    b.HasIndex("AssetId");

                    b.HasIndex("ConditionGradeId");

                    b.ToTable("AssetCondition", "Maintenance", t =>
                        {
                            t.HasCheckConstraint("CK_Maintenance_AssetCondition_HealthScore", "[HealthScorePercent] IS NULL OR ([HealthScorePercent] >= 0 AND [HealthScorePercent] <= 100)");
                        });
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.AssetConditionMeasurement", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("AssetConditionMeasurementId");

                    b.Property<long>("AssetConditionId")
                        .HasColumnType("bigint")
                        .HasColumnName("AssetConditionId");

                    b.Property<int>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("MeasuredAtUtc");

                    b.Property<double>("MeasuredValue")
                        .HasColumnType("float")
                        .HasColumnName("MeasuredValue");

                    b.Property<string>("MeasurementNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MeasurementNote");

                    b.Property<int?>("SignalId")
                        .HasColumnType("int")
                        .HasColumnName("SignalId");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_AssetConditionMeasurement");

                    b.HasIndex("AssetConditionId");

                    b.HasIndex("EngineeringUnitId");

                    b.HasIndex("SignalId");

                    b.ToTable("AssetConditionMeasurement", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.AssetCriticality", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AssetCriticalityId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_AssetCriticality");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Maintenance_AssetCriticality_Code");

                    b.ToTable("AssetCriticality", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.AssetStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AssetStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_AssetStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Maintenance_AssetStatus_Code");

                    b.ToTable("AssetStatus", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.ConditionGrade", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ConditionGradeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_ConditionGrade");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Maintenance_ConditionGrade_Code");

                    b.ToTable("ConditionGrade", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.DegradationMechanism", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("DegradationMechanismId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_DegradationMechanism");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Maintenance_DegradationMechanism_Code");

                    b.ToTable("DegradationMechanism", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.DegradationRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("DegradationRecordId");

                    b.Property<int?>("AssetComponentId")
                        .HasColumnType("int")
                        .HasColumnName("AssetComponentId");

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("AssetId");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ClosedAtUtc");

                    b.Property<int?>("ConditionGradeId")
                        .HasColumnType("int")
                        .HasColumnName("ConditionGradeId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<int>("DegradationMechanismId")
                        .HasColumnType("int")
                        .HasColumnName("DegradationMechanismId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Description");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DetectedAtUtc");

                    b.Property<int?>("DetectedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("DetectedByUserId");

                    b.Property<decimal?>("EstimatedRatePerYear")
                        .HasColumnType("decimal(12,6)")
                        .HasColumnName("EstimatedRatePerYear");

                    b.Property<int>("FindingSeverityId")
                        .HasColumnType("int")
                        .HasColumnName("FindingSeverityId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_DegradationRecord");

                    b.HasIndex("AssetComponentId");

                    b.HasIndex("AssetId");

                    b.HasIndex("ConditionGradeId");

                    b.HasIndex("DegradationMechanismId");

                    b.HasIndex("FindingSeverityId");

                    b.ToTable("DegradationRecord", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.DegradationTrendPoint", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("DegradationTrendPointId");

                    b.Property<long>("DegradationRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("DegradationRecordId");

                    b.Property<int>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<DateTime>("MeasuredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("MeasuredAtUtc");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Note");

                    b.Property<int?>("SourceSignalId")
                        .HasColumnType("int")
                        .HasColumnName("SourceSignalId");

                    b.Property<double>("Value")
                        .HasColumnType("float")
                        .HasColumnName("Value");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_DegradationTrendPoint");

                    b.HasIndex("DegradationRecordId");

                    b.HasIndex("EngineeringUnitId");

                    b.HasIndex("SourceSignalId");

                    b.ToTable("DegradationTrendPoint", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.FindingSeverity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("FindingSeverityId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_FindingSeverity");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Maintenance_FindingSeverity_Code");

                    b.ToTable("FindingSeverity", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.WorkOrder", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("WorkOrderId");

                    b.Property<int?>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("AssetId");

                    b.Property<int?>("AssignedPersonId")
                        .HasColumnType("int")
                        .HasColumnName("AssignedPersonId");

                    b.Property<int?>("AssignedTeamId")
                        .HasColumnType("int")
                        .HasColumnName("AssignedTeamId");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("MaintenancePlanId")
                        .HasColumnType("int")
                        .HasColumnName("MaintenancePlanId");

                    b.Property<int?>("MaintenanceWindowId")
                        .HasColumnType("int")
                        .HasColumnName("MaintenanceWindowId");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<long?>("OriginIncidentActionId")
                        .HasColumnType("bigint")
                        .HasColumnName("OriginIncidentActionId");

                    b.Property<long?>("OriginOperationalEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("OriginOperationalEventId");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("RequestedAtUtc");

                    b.Property<int?>("RequestedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("RequestedByUserId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("WorkOrderCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("WorkOrderStatusId")
                        .HasColumnType("int")
                        .HasColumnName("WorkOrderStatusId");

                    b.Property<int>("WorkOrderTypeId")
                        .HasColumnType("int")
                        .HasColumnName("WorkOrderTypeId");

                    b.Property<int>("WorkPriorityId")
                        .HasColumnType("int")
                        .HasColumnName("WorkPriorityId");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_WorkOrder");

                    b.HasIndex("AssetId");

                    b.HasIndex("UnitId");

                    b.HasIndex("WorkOrderCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Maintenance_WorkOrder_Code");

                    b.HasIndex("WorkOrderStatusId");

                    b.HasIndex("WorkOrderTypeId");

                    b.HasIndex("WorkPriorityId");

                    b.ToTable("WorkOrder", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.WorkOrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("WorkOrderStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_WorkOrderStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Maintenance_WorkOrderStatus_Code");

                    b.ToTable("WorkOrderStatus", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.WorkOrderType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("WorkOrderTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_WorkOrderType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Maintenance_WorkOrderType_Code");

                    b.ToTable("WorkOrderType", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.WorkPriority", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("WorkPriorityId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Maintenance_WorkPriority");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Maintenance_WorkPriority_Code");

                    b.ToTable("WorkPriority", "Maintenance");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", b =>
                {
                    b.Property<int>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Symbol");

                    b.HasKey("EngineeringUnitId");

                    b.ToTable("EngineeringUnit", "CorePlatform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.Maintenance.Infrastructure.Persistence.ExternalReferences.InstrumentationSignalReference", b =>
                {
                    b.Property<int>("SignalId")
                        .HasColumnType("int")
                        .HasColumnName("SignalId");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Tag");

                    b.HasKey("SignalId");

                    b.ToTable("Signal", "Instrumentation", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.Maintenance.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Code");

                    b.HasKey("UnitId");

                    b.ToTable("Unit", "ReactorFleet", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.Asset", b =>
                {
                    b.HasOne("Nexus1.Maintenance.Domain.AssetCategory", null)
                        .WithMany()
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_Asset_AssetCategory");

                    b.HasOne("Nexus1.Maintenance.Domain.AssetCriticality", null)
                        .WithMany()
                        .HasForeignKey("AssetCriticalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_Asset_AssetCriticality");

                    b.HasOne("Nexus1.Maintenance.Domain.AssetStatus", null)
                        .WithMany()
                        .HasForeignKey("AssetStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_Asset_AssetStatus");

                    b.HasOne("Nexus1.Maintenance.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_Asset_Unit");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.AssetComponent", b =>
                {
                    b.HasOne("Nexus1.Maintenance.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_AssetComponent_Asset");

                    b.HasOne("Nexus1.Maintenance.Domain.AssetComponent", null)
                        .WithMany()
                        .HasForeignKey("ParentAssetComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Maintenance_AssetComponent_Parent");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.AssetCondition", b =>
                {
                    b.HasOne("Nexus1.Maintenance.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_AssetCondition_Asset");

                    b.HasOne("Nexus1.Maintenance.Domain.ConditionGrade", null)
                        .WithMany()
                        .HasForeignKey("ConditionGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_AssetCondition_ConditionGrade");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.AssetConditionMeasurement", b =>
                {
                    b.HasOne("Nexus1.Maintenance.Domain.AssetCondition", null)
                        .WithMany()
                        .HasForeignKey("AssetConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_AssetConditionMeasurement_AssetCondition");

                    b.HasOne("Nexus1.Maintenance.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", null)
                        .WithMany()
                        .HasForeignKey("EngineeringUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_AssetConditionMeasurement_EngineeringUnit");

                    b.HasOne("Nexus1.Maintenance.Infrastructure.Persistence.ExternalReferences.InstrumentationSignalReference", null)
                        .WithMany()
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Maintenance_AssetConditionMeasurement_Signal");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.DegradationRecord", b =>
                {
                    b.HasOne("Nexus1.Maintenance.Domain.AssetComponent", null)
                        .WithMany()
                        .HasForeignKey("AssetComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Maintenance_DegradationRecord_AssetComponent");

                    b.HasOne("Nexus1.Maintenance.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_DegradationRecord_Asset");

                    b.HasOne("Nexus1.Maintenance.Domain.ConditionGrade", null)
                        .WithMany()
                        .HasForeignKey("ConditionGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Maintenance_DegradationRecord_ConditionGrade");

                    b.HasOne("Nexus1.Maintenance.Domain.DegradationMechanism", null)
                        .WithMany()
                        .HasForeignKey("DegradationMechanismId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_DegradationRecord_DegradationMechanism");

                    b.HasOne("Nexus1.Maintenance.Domain.FindingSeverity", null)
                        .WithMany()
                        .HasForeignKey("FindingSeverityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_DegradationRecord_FindingSeverity");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.DegradationTrendPoint", b =>
                {
                    b.HasOne("Nexus1.Maintenance.Domain.DegradationRecord", null)
                        .WithMany()
                        .HasForeignKey("DegradationRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_DegradationTrendPoint_DegradationRecord");

                    b.HasOne("Nexus1.Maintenance.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", null)
                        .WithMany()
                        .HasForeignKey("EngineeringUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_DegradationTrendPoint_EngineeringUnit");

                    b.HasOne("Nexus1.Maintenance.Infrastructure.Persistence.ExternalReferences.InstrumentationSignalReference", null)
                        .WithMany()
                        .HasForeignKey("SourceSignalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Maintenance_DegradationTrendPoint_SourceSignal");
                });

            modelBuilder.Entity("Nexus1.Maintenance.Domain.WorkOrder", b =>
                {
                    b.HasOne("Nexus1.Maintenance.Domain.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Maintenance_WorkOrder_Asset");

                    b.HasOne("Nexus1.Maintenance.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_WorkOrder_Unit");

                    b.HasOne("Nexus1.Maintenance.Domain.WorkOrderStatus", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_WorkOrder_Status");

                    b.HasOne("Nexus1.Maintenance.Domain.WorkOrderType", null)
                        .WithMany()
                        .HasForeignKey("WorkOrderTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_WorkOrder_Type");

                    b.HasOne("Nexus1.Maintenance.Domain.WorkPriority", null)
                        .WithMany()
                        .HasForeignKey("WorkPriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Maintenance_WorkOrder_Priority");
                });
#pragma warning restore 612, 618
        }
    }
}
