// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus1.Robotics.Infrastructure.Persistence;

#nullable disable

namespace Nexus1.Robotics.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RoboticsDbContext))]
    partial class RoboticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus1.Robotics.Domain.BatteryStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("BatteryStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_BatteryStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Robotics_BatteryStatus_Code");

                    b.ToTable("BatteryStatus", "Robotics");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.CommunicationStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("CommunicationStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_CommunicationStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Robotics_CommunicationStatus_Code");

                    b.ToTable("CommunicationStatus", "Robotics");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.Mission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("MissionId");

                    b.Property<DateTime?>("ActualEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovedByUserId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MissionPriorityId")
                        .HasColumnType("int")
                        .HasColumnName("MissionPriorityId");

                    b.Property<int>("MissionStatusId")
                        .HasColumnType("int")
                        .HasColumnName("MissionStatusId");

                    b.Property<int>("MissionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("MissionTypeId");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Objective")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("PlannedEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlannedStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("RequestedByUserId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_Mission");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Robotics_Mission_Code");

                    b.HasIndex("MissionPriorityId");

                    b.HasIndex("MissionStatusId");

                    b.HasIndex("MissionTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("Mission", "Robotics", t =>
                        {
                            t.HasCheckConstraint("CK_Robotics_Mission_ActualDateRange", "[ActualEndUtc] IS NULL OR [ActualStartUtc] IS NULL OR [ActualEndUtc] >= [ActualStartUtc]");

                            t.HasCheckConstraint("CK_Robotics_Mission_PlannedDateRange", "[PlannedEndUtc] IS NULL OR [PlannedStartUtc] IS NULL OR [PlannedEndUtc] >= [PlannedStartUtc]");
                        });
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.MissionEvent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("MissionEventId");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsFault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("MissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("MissionId");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("RecordedByUserId");

                    b.Property<int?>("RobotId")
                        .HasColumnType("int")
                        .HasColumnName("RobotId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_MissionEvent");

                    b.HasIndex("MissionId");

                    b.HasIndex("RobotId");

                    b.ToTable("MissionEvent", "Robotics");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.MissionPriority", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("MissionPriorityId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_MissionPriority");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Robotics_MissionPriority_Code");

                    b.ToTable("MissionPriority", "Robotics");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.MissionReadinessAssessment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("MissionReadinessAssessmentId");

                    b.Property<DateTime>("AssessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssessedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("AssessedByUserId");

                    b.Property<long>("MissionId")
                        .HasColumnType("bigint")
                        .HasColumnName("MissionId");

                    b.Property<int>("ReadinessStatusId")
                        .HasColumnType("int")
                        .HasColumnName("ReadinessStatusId");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_MissionReadinessAssessment");

                    b.HasIndex("MissionId");

                    b.HasIndex("ReadinessStatusId");

                    b.ToTable("MissionReadinessAssessment", "Robotics");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.MissionReadinessItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("MissionReadinessItemId");

                    b.Property<string>("CheckName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsBlocking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("MissionReadinessAssessmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("MissionReadinessAssessmentId");

                    b.Property<int>("ReadinessStatusId")
                        .HasColumnType("int")
                        .HasColumnName("ReadinessStatusId");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_MissionReadinessItem");

                    b.HasIndex("MissionReadinessAssessmentId");

                    b.HasIndex("ReadinessStatusId");

                    b.ToTable("MissionReadinessItem", "Robotics");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.MissionStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("MissionStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_MissionStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Robotics_MissionStatus_Code");

                    b.ToTable("MissionStatus", "Robotics");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.MissionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("MissionTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_MissionType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Robotics_MissionType_Code");

                    b.ToTable("MissionType", "Robotics");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.ReadinessStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ReadinessStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_ReadinessStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Robotics_ReadinessStatus_Code");

                    b.ToTable("ReadinessStatus", "Robotics");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.Robot", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RobotId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("CommissionedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<int?>("HomeUnitId")
                        .HasColumnType("int")
                        .HasColumnName("HomeUnitId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RetiredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RobotModelId")
                        .HasColumnType("int")
                        .HasColumnName("RobotModelId");

                    b.Property<int>("RobotStatusId")
                        .HasColumnType("int")
                        .HasColumnName("RobotStatusId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_Robot");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Robotics_Robot_Code");

                    b.HasIndex("HomeUnitId");

                    b.HasIndex("RobotModelId");

                    b.HasIndex("RobotStatusId");

                    b.ToTable("Robot", "Robotics");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.RobotHealthSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("RobotHealthSnapshotId");

                    b.Property<decimal?>("BatteryPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("BatteryStatusId")
                        .HasColumnType("int")
                        .HasColumnName("BatteryStatusId");

                    b.Property<int>("CommunicationStatusId")
                        .HasColumnType("int")
                        .HasColumnName("CommunicationStatusId");

                    b.Property<decimal?>("CpuLoadPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("EstimatedRuntimeMin")
                        .HasColumnType("int");

                    b.Property<int>("FaultCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RobotId")
                        .HasColumnType("int")
                        .HasColumnName("RobotId");

                    b.Property<DateTime>("SnapshotAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_RobotHealthSnapshot");

                    b.HasIndex("BatteryStatusId");

                    b.HasIndex("CommunicationStatusId");

                    b.HasIndex("RobotId");

                    b.ToTable("RobotHealthSnapshot", "Robotics", t =>
                        {
                            t.HasCheckConstraint("CK_Robotics_RobotHealthSnapshot_BatteryPercent", "[BatteryPercent] IS NULL OR ([BatteryPercent] BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("CK_Robotics_RobotHealthSnapshot_CpuLoadPercent", "[CpuLoadPercent] IS NULL OR ([CpuLoadPercent] BETWEEN 0 AND 100)");
                        });
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.RobotModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RobotModelId");

                    b.Property<decimal?>("BatteryCapacityWh")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAutonomousCapable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("MaxPayloadKg")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal?>("MaxSpeedMps")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<int?>("NominalRuntimeMin")
                        .HasColumnType("int");

                    b.Property<int>("RobotTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RobotTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_RobotModel");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Robotics_RobotModel_Code");

                    b.HasIndex("RobotTypeId");

                    b.ToTable("RobotModel", "Robotics", t =>
                        {
                            t.HasCheckConstraint("CK_Robotics_RobotModel_MaxPayloadKg", "[MaxPayloadKg] IS NULL OR [MaxPayloadKg] >= 0");

                            t.HasCheckConstraint("CK_Robotics_RobotModel_MaxSpeedMps", "[MaxSpeedMps] IS NULL OR [MaxSpeedMps] >= 0");
                        });
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.RobotStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RobotStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_RobotStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Robotics_RobotStatus_Code");

                    b.ToTable("RobotStatus", "Robotics");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.RobotType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RobotTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_Robotics_RobotType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Robotics_RobotType_Code");

                    b.ToTable("RobotType", "Robotics");
                });

            modelBuilder.Entity("Nexus1.Robotics.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Code");

                    b.HasKey("UnitId");

                    b.ToTable("Unit", "ReactorFleet", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.Mission", b =>
                {
                    b.HasOne("Nexus1.Robotics.Domain.MissionPriority", null)
                        .WithMany()
                        .HasForeignKey("MissionPriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_Mission_MissionPriority");

                    b.HasOne("Nexus1.Robotics.Domain.MissionStatus", null)
                        .WithMany()
                        .HasForeignKey("MissionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_Mission_MissionStatus");

                    b.HasOne("Nexus1.Robotics.Domain.MissionType", null)
                        .WithMany()
                        .HasForeignKey("MissionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_Mission_MissionType");

                    b.HasOne("Nexus1.Robotics.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_Mission_Unit");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.MissionEvent", b =>
                {
                    b.HasOne("Nexus1.Robotics.Domain.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_MissionEvent_Mission");

                    b.HasOne("Nexus1.Robotics.Domain.Robot", null)
                        .WithMany()
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Robotics_MissionEvent_Robot");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.MissionReadinessAssessment", b =>
                {
                    b.HasOne("Nexus1.Robotics.Domain.Mission", null)
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_MissionReadinessAssessment_Mission");

                    b.HasOne("Nexus1.Robotics.Domain.ReadinessStatus", null)
                        .WithMany()
                        .HasForeignKey("ReadinessStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_MissionReadinessAssessment_ReadinessStatus");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.MissionReadinessItem", b =>
                {
                    b.HasOne("Nexus1.Robotics.Domain.MissionReadinessAssessment", null)
                        .WithMany()
                        .HasForeignKey("MissionReadinessAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_MissionReadinessItem_MissionReadinessAssessment");

                    b.HasOne("Nexus1.Robotics.Domain.ReadinessStatus", null)
                        .WithMany()
                        .HasForeignKey("ReadinessStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_MissionReadinessItem_ReadinessStatus");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.Robot", b =>
                {
                    b.HasOne("Nexus1.Robotics.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("HomeUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Robotics_Robot_Unit");

                    b.HasOne("Nexus1.Robotics.Domain.RobotModel", null)
                        .WithMany()
                        .HasForeignKey("RobotModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_Robot_RobotModel");

                    b.HasOne("Nexus1.Robotics.Domain.RobotStatus", null)
                        .WithMany()
                        .HasForeignKey("RobotStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_Robot_RobotStatus");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.RobotHealthSnapshot", b =>
                {
                    b.HasOne("Nexus1.Robotics.Domain.BatteryStatus", null)
                        .WithMany()
                        .HasForeignKey("BatteryStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_RobotHealthSnapshot_BatteryStatus");

                    b.HasOne("Nexus1.Robotics.Domain.CommunicationStatus", null)
                        .WithMany()
                        .HasForeignKey("CommunicationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_RobotHealthSnapshot_CommunicationStatus");

                    b.HasOne("Nexus1.Robotics.Domain.Robot", null)
                        .WithMany()
                        .HasForeignKey("RobotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_RobotHealthSnapshot_Robot");
                });

            modelBuilder.Entity("Nexus1.Robotics.Domain.RobotModel", b =>
                {
                    b.HasOne("Nexus1.Robotics.Domain.RobotType", null)
                        .WithMany()
                        .HasForeignKey("RobotTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Robotics_RobotModel_RobotType");
                });
#pragma warning restore 612, 618
        }
    }
}
