// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus1.AlarmManagement.Infrastructure.Persistence;

#nullable disable

namespace Nexus1.AlarmManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlarmManagementDbContext))]
    partial class AlarmManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus1.AlarmManagement.Domain.AlarmDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AlarmDefinitionId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ThresholdValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_AlarmManagement_AlarmDefinition");

                    b.HasIndex("UnitId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_AlarmManagement_AlarmDefinition_UnitId_Code");

                    b.ToTable("AlarmDefinition", "AlarmManagement");
                });

            modelBuilder.Entity("Nexus1.AlarmManagement.Domain.AlarmEvent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("AlarmEventId");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AcknowledgedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AcknowledgedByUserId");

                    b.Property<int>("AlarmDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("AlarmDefinitionId");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RaisedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("SourceValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("ThresholdValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_AlarmManagement_AlarmEvent");

                    b.HasIndex("AlarmDefinitionId", "RaisedAtUtc")
                        .HasDatabaseName("IX_AlarmManagement_AlarmEvent_AlarmDefinitionId_RaisedAtUtc");

                    b.HasIndex("UnitId", "RaisedAtUtc")
                        .HasDatabaseName("IX_AlarmManagement_AlarmEvent_UnitId_RaisedAtUtc");

                    b.ToTable("AlarmEvent", "AlarmManagement");
                });

            modelBuilder.Entity("Nexus1.AlarmManagement.Domain.AlarmFlood", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("AlarmFloodId");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_AlarmManagement_AlarmFlood");

                    b.HasIndex("UnitId", "StartedAtUtc")
                        .HasDatabaseName("IX_AlarmManagement_AlarmFlood_UnitId_StartedAtUtc");

                    b.ToTable("AlarmFlood", "AlarmManagement");
                });

            modelBuilder.Entity("Nexus1.AlarmManagement.Infrastructure.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MessageId");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<byte[]>("EnvelopeBytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("EnvelopeSha256")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.Property<string>("SpanId")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("StoredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("TraceFlags")
                        .HasColumnType("tinyint");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TraceState")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("MessageId")
                        .HasName("PK_messaging_OutboxMessage");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("IX_messaging_OutboxMessage_ProcessedAtUtc");

                    b.ToTable("OutboxMessage", "messaging");
                });
#pragma warning restore 612, 618
        }
    }
}
