// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus1.Instrumentation.Infrastructure.Persistence;

#nullable disable

namespace Nexus1.Instrumentation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InstrumentationDbContext))]
    [Migration("20260816161628_InitialInstrumentationSchema")]
    partial class InitialInstrumentationSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.AcquisitionConnection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AcquisitionConnectionId");

                    b.Property<int>("ChannelStatusId")
                        .HasColumnType("int")
                        .HasColumnName("ChannelStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataAcquisitionNodeId")
                        .HasColumnType("int")
                        .HasColumnName("DataAcquisitionNodeId");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<int?>("PollIntervalMs")
                        .HasColumnType("int");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_AcquisitionConnection");

                    b.HasIndex("ChannelStatusId");

                    b.HasIndex("DataAcquisitionNodeId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_AcquisitionConnection_Node_Code");

                    b.ToTable("AcquisitionConnection", "Instrumentation", t =>
                        {
                            t.HasCheckConstraint("CK_Instrumentation_AcquisitionConnection_PollInterval", "[PollIntervalMs] IS NULL OR [PollIntervalMs] > 0");
                        });
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.AcquisitionPoint", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AcquisitionPointId");

                    b.Property<int>("AcquisitionConnectionId")
                        .HasColumnType("int")
                        .HasColumnName("AcquisitionConnectionId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("OffsetValue")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("RawAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RawDataType")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal?>("ScaleFactor")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_AcquisitionPoint");

                    b.HasIndex("AcquisitionConnectionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_AcquisitionPoint_Connection_Code");

                    b.ToTable("AcquisitionPoint", "Instrumentation");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.ChannelStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ChannelStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_ChannelStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_ChannelStatus_Code");

                    b.ToTable("ChannelStatus", "Instrumentation");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.DataAcquisitionNode", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("DataAcquisitionNodeId");

                    b.Property<int>("ChannelStatusId")
                        .HasColumnType("int")
                        .HasColumnName("ChannelStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HostName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NetworkZone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_DataAcquisitionNode");

                    b.HasIndex("ChannelStatusId");

                    b.HasIndex("UnitId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_DataAcquisitionNode_Unit_Code");

                    b.ToTable("DataAcquisitionNode", "Instrumentation");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.HistorianRetentionClass", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("HistorianRetentionClassId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_HistorianRetentionClass");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_HistorianRetentionClass_Code");

                    b.ToTable("HistorianRetentionClass", "Instrumentation");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.Measurement", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("MeasurementId");

                    b.Property<DateTime>("InsertedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("bit");

                    b.Property<int>("MeasurementSourceId")
                        .HasColumnType("int")
                        .HasColumnName("MeasurementSourceId");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("float");

                    b.Property<int>("SignalId")
                        .HasColumnType("int")
                        .HasColumnName("SignalId");

                    b.Property<int>("SignalQualityId")
                        .HasColumnType("int")
                        .HasColumnName("SignalQualityId");

                    b.Property<string>("TextValue")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_Measurement");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("MeasurementSourceId");

                    b.HasIndex("SignalQualityId");

                    b.HasIndex("SignalId", "TimestampUtc")
                        .HasDatabaseName("IX_Instrumentation_Measurement_SignalId_TimestampUtc");

                    b.ToTable("Measurement", "Instrumentation", t =>
                        {
                            t.HasCheckConstraint("CK_Instrumentation_Measurement_OneValue", "[NumericValue] IS NOT NULL OR [TextValue] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.MeasurementSource", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("MeasurementSourceId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_MeasurementSource");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_MeasurementSource_Code");

                    b.ToTable("MeasurementSource", "Instrumentation");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.SamplingMode", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SamplingModeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_SamplingMode");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_SamplingMode_Code");

                    b.ToTable("SamplingMode", "Instrumentation");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.Signal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SignalId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentId");

                    b.Property<int>("HistorianRetentionClassId")
                        .HasColumnType("int")
                        .HasColumnName("HistorianRetentionClassId");

                    b.Property<bool>("IsHistorized")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSafetyRelated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("NormalMax")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("NormalMin")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("PlantSystemId")
                        .HasColumnType("int")
                        .HasColumnName("PlantSystemId");

                    b.Property<int?>("PrecisionDigits")
                        .HasColumnType("int");

                    b.Property<int>("SamplingModeId")
                        .HasColumnType("int")
                        .HasColumnName("SamplingModeId");

                    b.Property<decimal?>("ScanRateHz")
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("SignalCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("SignalCategoryId");

                    b.Property<int>("SignalRoleId")
                        .HasColumnType("int")
                        .HasColumnName("SignalRoleId");

                    b.Property<int>("SignalTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SignalTypeId");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_Signal");

                    b.HasIndex("EngineeringUnitId");

                    b.HasIndex("HistorianRetentionClassId");

                    b.HasIndex("SamplingModeId");

                    b.HasIndex("SignalCategoryId");

                    b.HasIndex("SignalRoleId");

                    b.HasIndex("SignalTypeId");

                    b.HasIndex("Tag")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_Signal_Tag");

                    b.HasIndex("UnitId");

                    b.ToTable("Signal", "Instrumentation", t =>
                        {
                            t.HasCheckConstraint("CK_Instrumentation_Signal_NormalRange", "[NormalMin] IS NULL OR [NormalMax] IS NULL OR [NormalMax] > [NormalMin]");

                            t.HasCheckConstraint("CK_Instrumentation_Signal_ScanRate", "[ScanRateHz] IS NULL OR [ScanRateHz] > 0");
                        });
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.SignalCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SignalCategoryId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_SignalCategory");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_SignalCategory_Code");

                    b.ToTable("SignalCategory", "Instrumentation");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.SignalMapping", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SignalMappingId");

                    b.Property<int>("AcquisitionPointId")
                        .HasColumnType("int")
                        .HasColumnName("AcquisitionPointId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SignalId")
                        .HasColumnType("int")
                        .HasColumnName("SignalId");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_SignalMapping");

                    b.HasIndex("AcquisitionPointId");

                    b.HasIndex("SignalId", "AcquisitionPointId", "EffectiveFromUtc")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_SignalMapping_Signal_Point_From");

                    b.ToTable("SignalMapping", "Instrumentation", t =>
                        {
                            t.HasCheckConstraint("CK_Instrumentation_SignalMapping_Effective", "[EffectiveToUtc] IS NULL OR [EffectiveToUtc] > [EffectiveFromUtc]");
                        });
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.SignalQuality", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SignalQualityId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_SignalQuality");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_SignalQuality_Code");

                    b.ToTable("SignalQuality", "Instrumentation");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.SignalQualityEvent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("SignalQualityEventId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SignalId")
                        .HasColumnType("int")
                        .HasColumnName("SignalId");

                    b.Property<int>("SignalQualityId")
                        .HasColumnType("int")
                        .HasColumnName("SignalQualityId");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_SignalQualityEvent");

                    b.HasIndex("SignalQualityId");

                    b.HasIndex("SignalId", "EndedAtUtc")
                        .HasDatabaseName("IX_Instrumentation_SignalQualityEvent_SignalId_EndedAtUtc");

                    b.ToTable("SignalQualityEvent", "Instrumentation", t =>
                        {
                            t.HasCheckConstraint("CK_Instrumentation_SignalQualityEvent_Time", "[EndedAtUtc] IS NULL OR [EndedAtUtc] > [StartedAtUtc]");
                        });
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.SignalRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SignalRoleId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_SignalRole");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_SignalRole_Code");

                    b.ToTable("SignalRole", "Instrumentation");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.SignalType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SignalTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Instrumentation_SignalType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Instrumentation_SignalType_Code");

                    b.ToTable("SignalType", "Instrumentation");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", b =>
                {
                    b.Property<int>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Symbol");

                    b.HasKey("EngineeringUnitId");

                    b.ToTable("EngineeringUnit", "CorePlatform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Code");

                    b.HasKey("UnitId");

                    b.ToTable("Unit", "ReactorFleet", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.AcquisitionConnection", b =>
                {
                    b.HasOne("Nexus1.Instrumentation.Domain.ChannelStatus", null)
                        .WithMany()
                        .HasForeignKey("ChannelStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_AcquisitionConnection_ChannelStatus");

                    b.HasOne("Nexus1.Instrumentation.Domain.DataAcquisitionNode", null)
                        .WithMany()
                        .HasForeignKey("DataAcquisitionNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_AcquisitionConnection_DataAcquisitionNode");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.AcquisitionPoint", b =>
                {
                    b.HasOne("Nexus1.Instrumentation.Domain.AcquisitionConnection", null)
                        .WithMany()
                        .HasForeignKey("AcquisitionConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_AcquisitionPoint_AcquisitionConnection");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.DataAcquisitionNode", b =>
                {
                    b.HasOne("Nexus1.Instrumentation.Domain.ChannelStatus", null)
                        .WithMany()
                        .HasForeignKey("ChannelStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_DataAcquisitionNode_ChannelStatus");

                    b.HasOne("Nexus1.Instrumentation.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_DataAcquisitionNode_Unit");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.Measurement", b =>
                {
                    b.HasOne("Nexus1.Instrumentation.Domain.MeasurementSource", null)
                        .WithMany()
                        .HasForeignKey("MeasurementSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_Measurement_MeasurementSource");

                    b.HasOne("Nexus1.Instrumentation.Domain.Signal", null)
                        .WithMany()
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_Measurement_Signal");

                    b.HasOne("Nexus1.Instrumentation.Domain.SignalQuality", null)
                        .WithMany()
                        .HasForeignKey("SignalQualityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_Measurement_SignalQuality");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.Signal", b =>
                {
                    b.HasOne("Nexus1.Instrumentation.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", null)
                        .WithMany()
                        .HasForeignKey("EngineeringUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_Signal_EngineeringUnit");

                    b.HasOne("Nexus1.Instrumentation.Domain.HistorianRetentionClass", null)
                        .WithMany()
                        .HasForeignKey("HistorianRetentionClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_Signal_HistorianRetentionClass");

                    b.HasOne("Nexus1.Instrumentation.Domain.SamplingMode", null)
                        .WithMany()
                        .HasForeignKey("SamplingModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_Signal_SamplingMode");

                    b.HasOne("Nexus1.Instrumentation.Domain.SignalCategory", null)
                        .WithMany()
                        .HasForeignKey("SignalCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_Signal_SignalCategory");

                    b.HasOne("Nexus1.Instrumentation.Domain.SignalRole", null)
                        .WithMany()
                        .HasForeignKey("SignalRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_Signal_SignalRole");

                    b.HasOne("Nexus1.Instrumentation.Domain.SignalType", null)
                        .WithMany()
                        .HasForeignKey("SignalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_Signal_SignalType");

                    b.HasOne("Nexus1.Instrumentation.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_Signal_Unit");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.SignalMapping", b =>
                {
                    b.HasOne("Nexus1.Instrumentation.Domain.AcquisitionPoint", null)
                        .WithMany()
                        .HasForeignKey("AcquisitionPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_SignalMapping_AcquisitionPoint");

                    b.HasOne("Nexus1.Instrumentation.Domain.Signal", null)
                        .WithMany()
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_SignalMapping_Signal");
                });

            modelBuilder.Entity("Nexus1.Instrumentation.Domain.SignalQualityEvent", b =>
                {
                    b.HasOne("Nexus1.Instrumentation.Domain.Signal", null)
                        .WithMany()
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_SignalQualityEvent_Signal");

                    b.HasOne("Nexus1.Instrumentation.Domain.SignalQuality", null)
                        .WithMany()
                        .HasForeignKey("SignalQualityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Instrumentation_SignalQualityEvent_SignalQuality");
                });
#pragma warning restore 612, 618
        }
    }
}
