// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus1.RootCause.Infrastructure.Persistence;

#nullable disable

namespace Nexus1.RootCause.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RootCauseDbContext))]
    [Migration("20260815053325_InitialRootCauseSchema")]
    partial class InitialRootCauseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus1.RootCause.Domain.AnalysisHypothesis", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AnalysisHypothesisId");

                    b.Property<string>("HypothesisStatement")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RejectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("RootCauseAnalysisId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_RootCause_AnalysisHypothesis");

                    b.HasIndex("RootCauseAnalysisId");

                    b.ToTable("AnalysisHypothesis", "RootCause");
                });

            modelBuilder.Entity("Nexus1.RootCause.Domain.HypothesisEvidence", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("HypothesisEvidenceId");

                    b.Property<int>("AnalysisHypothesisId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_RootCause_HypothesisEvidence");

                    b.HasIndex("AnalysisHypothesisId");

                    b.ToTable("HypothesisEvidence", "RootCause");
                });

            modelBuilder.Entity("Nexus1.RootCause.Domain.RootCauseAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("RootCauseAnalysisId");

                    b.Property<long>("AlarmFloodId")
                        .HasColumnType("bigint")
                        .HasColumnName("AlarmFloodId");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OpenedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("Verdict")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK_RootCause_RootCauseAnalysis");

                    b.HasIndex("AlarmFloodId")
                        .HasDatabaseName("IX_RootCause_RootCauseAnalysis_AlarmFloodId");

                    b.ToTable("RootCauseAnalysis", "RootCause");
                });

            modelBuilder.Entity("Nexus1.RootCause.Domain.AnalysisHypothesis", b =>
                {
                    b.HasOne("Nexus1.RootCause.Domain.RootCauseAnalysis", null)
                        .WithMany("Hypotheses")
                        .HasForeignKey("RootCauseAnalysisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RootCause_AnalysisHypothesis_RootCauseAnalysisId");
                });

            modelBuilder.Entity("Nexus1.RootCause.Domain.HypothesisEvidence", b =>
                {
                    b.HasOne("Nexus1.RootCause.Domain.AnalysisHypothesis", null)
                        .WithMany("Evidence")
                        .HasForeignKey("AnalysisHypothesisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RootCause_HypothesisEvidence_AnalysisHypothesisId");
                });

            modelBuilder.Entity("Nexus1.RootCause.Domain.AnalysisHypothesis", b =>
                {
                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("Nexus1.RootCause.Domain.RootCauseAnalysis", b =>
                {
                    b.Navigation("Hypotheses");
                });
#pragma warning restore 612, 618
        }
    }
}
