<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Nexus1.RootCause.Host-794305d3-88ef-4fdc-b363-bc534ea235b7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Contexts\RootCause\Nexus1.RootCause.Application\Nexus1.RootCause.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\RootCause\Nexus1.RootCause.Infrastructure\Nexus1.RootCause.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Nexus1.BuildingBlocks.Application\Nexus1.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Nexus1.ServiceDefaults\Nexus1.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
