// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus1.DigitalTwin.Infrastructure.Persistence;

#nullable disable

namespace Nexus1.DigitalTwin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DigitalTwinDbContext))]
    [Migration("20260816195722_InitialDigitalTwinSchema")]
    partial class InitialDigitalTwinSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.BindingRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("BindingRoleId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_BindingRole");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_BindingRole_Code");

                    b.ToTable("BindingRole", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.BindingStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("BindingStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_BindingStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_BindingStatus_Code");

                    b.ToTable("BindingStatus", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.DivergenceSeverity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("DivergenceSeverityId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_DivergenceSeverity");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_DivergenceSeverity_Code");

                    b.ToTable("DivergenceSeverity", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.DivergenceStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("DivergenceStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_DivergenceStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_DivergenceStatus_Code");

                    b.ToTable("DivergenceStatus", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.ModelVariableType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ModelVariableTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_ModelVariableType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_ModelVariableType_Code");

                    b.ToTable("ModelVariableType", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.SignalBinding", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SignalBindingId");

                    b.Property<int>("BindingRoleId")
                        .HasColumnType("int")
                        .HasColumnName("BindingRoleId");

                    b.Property<int>("BindingStatusId")
                        .HasColumnType("int")
                        .HasColumnName("BindingStatusId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("ModelVariable")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<decimal?>("OffsetValue")
                        .HasColumnType("decimal(18,8)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("ScaleFactor")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("SignalId")
                        .HasColumnType("int")
                        .HasColumnName("SignalId");

                    b.Property<double?>("ToleranceAbs")
                        .HasColumnType("float");

                    b.Property<double?>("TolerancePercent")
                        .HasColumnType("float");

                    b.Property<int>("TwinModelId")
                        .HasColumnType("int")
                        .HasColumnName("TwinModelId");

                    b.Property<int>("TwinVariableId")
                        .HasColumnType("int")
                        .HasColumnName("TwinVariableId");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_SignalBinding");

                    b.HasIndex("BindingRoleId");

                    b.HasIndex("BindingStatusId");

                    b.HasIndex("SignalId");

                    b.HasIndex("TwinVariableId");

                    b.HasIndex("TwinModelId", "TwinVariableId", "SignalId")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_SignalBinding_Model_Variable_Signal");

                    b.ToTable("SignalBinding", "DigitalTwin", t =>
                        {
                            t.HasCheckConstraint("CK_DigitalTwin_SignalBinding_EffectiveRange", "[EffectiveToUtc] IS NULL OR [EffectiveToUtc] > [EffectiveFromUtc]");
                        });
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.SnapshotReason", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SnapshotReasonId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_SnapshotReason");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_SnapshotReason_Code");

                    b.ToTable("SnapshotReason", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.SolverType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SolverTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_SolverType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_SolverType_Code");

                    b.ToTable("SolverType", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinDivergence", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("TwinDivergenceId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("DeltaPercent")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("DeltaPercent");

                    b.Property<double>("DeltaValue")
                        .HasColumnType("float")
                        .HasColumnName("DeltaValue");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("DetectedAtUtc");

                    b.Property<int>("DivergenceSeverityId")
                        .HasColumnType("int")
                        .HasColumnName("DivergenceSeverityId");

                    b.Property<int>("DivergenceStatusId")
                        .HasColumnType("int")
                        .HasColumnName("DivergenceStatusId");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Explanation");

                    b.Property<double>("MeasuredValue")
                        .HasColumnType("float")
                        .HasColumnName("MeasuredValue");

                    b.Property<double>("ModeledValue")
                        .HasColumnType("float")
                        .HasColumnName("ModeledValue");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SignalId")
                        .HasColumnType("int")
                        .HasColumnName("SignalId");

                    b.Property<double?>("ThresholdAbs")
                        .HasColumnType("float")
                        .HasColumnName("ThresholdAbs");

                    b.Property<decimal?>("ThresholdPercent")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("ThresholdPercent");

                    b.Property<long>("TwinSnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("TwinSnapshotId");

                    b.Property<int?>("TwinVariableId")
                        .HasColumnType("int")
                        .HasColumnName("TwinVariableId");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_TwinDivergence");

                    b.HasIndex("DivergenceSeverityId");

                    b.HasIndex("DivergenceStatusId");

                    b.HasIndex("SignalId");

                    b.HasIndex("TwinSnapshotId");

                    b.HasIndex("TwinVariableId");

                    b.ToTable("TwinDivergence", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinDivergenceReview", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("TwinDivergenceReviewId");

                    b.Property<string>("CorrectiveAction")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("CorrectiveAction");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DivergenceStatusId")
                        .HasColumnType("int")
                        .HasColumnName("DivergenceStatusId");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("ReviewNote");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReviewedAtUtc");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ReviewedByUserId");

                    b.Property<long>("TwinDivergenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("TwinDivergenceId");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_TwinDivergenceReview");

                    b.HasIndex("DivergenceStatusId");

                    b.HasIndex("TwinDivergenceId");

                    b.ToTable("TwinDivergenceReview", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinFidelityLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("TwinFidelityLevelId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_TwinFidelityLevel");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_TwinFidelityLevel_Code");

                    b.ToTable("TwinFidelityLevel", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("TwinModelId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsAuthoritative")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("ModelOwner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TwinFidelityLevelId")
                        .HasColumnType("int")
                        .HasColumnName("TwinFidelityLevelId");

                    b.Property<int>("TwinModelStatusId")
                        .HasColumnType("int")
                        .HasColumnName("TwinModelStatusId");

                    b.Property<int>("TwinModelTypeId")
                        .HasColumnType("int")
                        .HasColumnName("TwinModelTypeId");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_TwinModel");

                    b.HasIndex("TwinFidelityLevelId");

                    b.HasIndex("TwinModelStatusId");

                    b.HasIndex("TwinModelTypeId");

                    b.HasIndex("UnitId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_TwinModel_Unit_Code");

                    b.ToTable("TwinModel", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinModelStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("TwinModelStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_TwinModelStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_TwinModelStatus_Code");

                    b.ToTable("TwinModelStatus", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinModelType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("TwinModelTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_TwinModelType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_TwinModelType_Code");

                    b.ToTable("TwinModelType", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinModelVersion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("TwinModelVersionId");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ApprovedByUserId");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<byte[]>("ModelHash")
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<DateTime?>("ReleasedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SolverTypeId")
                        .HasColumnType("int")
                        .HasColumnName("SolverTypeId");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TwinModelId")
                        .HasColumnType("int")
                        .HasColumnName("TwinModelId");

                    b.Property<int>("ValidationStatusId")
                        .HasColumnType("int")
                        .HasColumnName("ValidationStatusId");

                    b.Property<string>("VersionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_TwinModelVersion");

                    b.HasIndex("SolverTypeId");

                    b.HasIndex("ValidationStatusId");

                    b.HasIndex("TwinModelId", "VersionCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_TwinModelVersion_Model_Version");

                    b.ToTable("TwinModelVersion", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinRuntimeSession", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("TwinRuntimeSessionId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("RuntimeMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SessionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StartedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("StartedByUserId");

                    b.Property<int>("TwinModelVersionId")
                        .HasColumnType("int")
                        .HasColumnName("TwinModelVersionId");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_TwinRuntimeSession");

                    b.HasIndex("SessionCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_TwinRuntimeSession_Code");

                    b.HasIndex("TwinModelVersionId");

                    b.ToTable("TwinRuntimeSession", "DigitalTwin", t =>
                        {
                            t.HasCheckConstraint("CK_DigitalTwin_TwinRuntimeSession_TimeRange", "[EndedAtUtc] IS NULL OR [EndedAtUtc] > [StartedAtUtc]");
                        });
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("TwinSnapshotId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("SnapshotAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("SnapshotAtUtc");

                    b.Property<int>("SnapshotReasonId")
                        .HasColumnType("int")
                        .HasColumnName("SnapshotReasonId");

                    b.Property<byte[]>("StateVectorHash")
                        .HasColumnType("varbinary(32)")
                        .HasColumnName("StateVectorHash");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SummaryJson");

                    b.Property<long?>("TimeStepIndex")
                        .HasColumnType("bigint")
                        .HasColumnName("TimeStepIndex");

                    b.Property<long>("TwinRuntimeSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("TwinRuntimeSessionId");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_TwinSnapshot");

                    b.HasIndex("SnapshotReasonId");

                    b.HasIndex("TwinRuntimeSessionId");

                    b.ToTable("TwinSnapshot", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinSnapshotValue", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("TwinSnapshotValueId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("JsonValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JsonValue");

                    b.Property<double?>("NumericValue")
                        .HasColumnType("float")
                        .HasColumnName("NumericValue");

                    b.Property<string>("TextValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("TextValue");

                    b.Property<long>("TwinSnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("TwinSnapshotId");

                    b.Property<int>("TwinVariableId")
                        .HasColumnType("int")
                        .HasColumnName("TwinVariableId");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_TwinSnapshotValue");

                    b.HasIndex("TwinVariableId");

                    b.HasIndex("TwinSnapshotId", "TwinVariableId")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_TwinSnapshotValue_Snapshot_Variable");

                    b.ToTable("TwinSnapshotValue", "DigitalTwin", t =>
                        {
                            t.HasCheckConstraint("CK_DigitalTwin_TwinSnapshotValue_OneValue", "[NumericValue] IS NOT NULL OR [TextValue] IS NOT NULL OR [JsonValue] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinVariable", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("TwinVariableId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStateVariable")
                        .HasColumnType("bit");

                    b.Property<double?>("LowerBound")
                        .HasColumnType("float");

                    b.Property<int>("ModelVariableTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ModelVariableTypeId");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TwinModelId")
                        .HasColumnType("int")
                        .HasColumnName("TwinModelId");

                    b.Property<double?>("UpperBound")
                        .HasColumnType("float");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_TwinVariable");

                    b.HasIndex("EngineeringUnitId");

                    b.HasIndex("ModelVariableTypeId");

                    b.HasIndex("TwinModelId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_TwinVariable_Model_Code");

                    b.ToTable("TwinVariable", "DigitalTwin", t =>
                        {
                            t.HasCheckConstraint("CK_DigitalTwin_TwinVariable_Bounds", "[LowerBound] IS NULL OR [UpperBound] IS NULL OR [LowerBound] <= [UpperBound]");
                        });
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.ValidationStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ValidationStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_DigitalTwin_ValidationStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DigitalTwin_ValidationStatus_Code");

                    b.ToTable("ValidationStatus", "DigitalTwin");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", b =>
                {
                    b.Property<int>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Symbol");

                    b.HasKey("EngineeringUnitId");

                    b.ToTable("EngineeringUnit", "CorePlatform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Infrastructure.Persistence.ExternalReferences.InstrumentationSignalReference", b =>
                {
                    b.Property<int>("SignalId")
                        .HasColumnType("int")
                        .HasColumnName("SignalId");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Tag");

                    b.HasKey("SignalId");

                    b.ToTable("Signal", "Instrumentation", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Code");

                    b.HasKey("UnitId");

                    b.ToTable("Unit", "ReactorFleet", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.SignalBinding", b =>
                {
                    b.HasOne("Nexus1.DigitalTwin.Domain.BindingRole", null)
                        .WithMany()
                        .HasForeignKey("BindingRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_SignalBinding_BindingRole");

                    b.HasOne("Nexus1.DigitalTwin.Domain.BindingStatus", null)
                        .WithMany()
                        .HasForeignKey("BindingStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_SignalBinding_BindingStatus");

                    b.HasOne("Nexus1.DigitalTwin.Infrastructure.Persistence.ExternalReferences.InstrumentationSignalReference", null)
                        .WithMany()
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_SignalBinding_Signal");

                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinModel", null)
                        .WithMany()
                        .HasForeignKey("TwinModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_SignalBinding_TwinModel");

                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinVariable", null)
                        .WithMany()
                        .HasForeignKey("TwinVariableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_SignalBinding_TwinVariable");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinDivergence", b =>
                {
                    b.HasOne("Nexus1.DigitalTwin.Domain.DivergenceSeverity", null)
                        .WithMany()
                        .HasForeignKey("DivergenceSeverityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinDivergence_DivergenceSeverity");

                    b.HasOne("Nexus1.DigitalTwin.Domain.DivergenceStatus", null)
                        .WithMany()
                        .HasForeignKey("DivergenceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinDivergence_DivergenceStatus");

                    b.HasOne("Nexus1.DigitalTwin.Infrastructure.Persistence.ExternalReferences.InstrumentationSignalReference", null)
                        .WithMany()
                        .HasForeignKey("SignalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinDivergence_Signal");

                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinSnapshot", null)
                        .WithMany()
                        .HasForeignKey("TwinSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinDivergence_TwinSnapshot");

                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinVariable", null)
                        .WithMany()
                        .HasForeignKey("TwinVariableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DigitalTwin_TwinDivergence_TwinVariable");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinDivergenceReview", b =>
                {
                    b.HasOne("Nexus1.DigitalTwin.Domain.DivergenceStatus", null)
                        .WithMany()
                        .HasForeignKey("DivergenceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinDivergenceReview_DivergenceStatus");

                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinDivergence", null)
                        .WithMany()
                        .HasForeignKey("TwinDivergenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinDivergenceReview_TwinDivergence");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinModel", b =>
                {
                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinFidelityLevel", null)
                        .WithMany()
                        .HasForeignKey("TwinFidelityLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinModel_TwinFidelityLevel");

                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinModelStatus", null)
                        .WithMany()
                        .HasForeignKey("TwinModelStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinModel_TwinModelStatus");

                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinModelType", null)
                        .WithMany()
                        .HasForeignKey("TwinModelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinModel_TwinModelType");

                    b.HasOne("Nexus1.DigitalTwin.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinModel_Unit");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinModelVersion", b =>
                {
                    b.HasOne("Nexus1.DigitalTwin.Domain.SolverType", null)
                        .WithMany()
                        .HasForeignKey("SolverTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinModelVersion_SolverType");

                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinModel", null)
                        .WithMany()
                        .HasForeignKey("TwinModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinModelVersion_TwinModel");

                    b.HasOne("Nexus1.DigitalTwin.Domain.ValidationStatus", null)
                        .WithMany()
                        .HasForeignKey("ValidationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinModelVersion_ValidationStatus");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinRuntimeSession", b =>
                {
                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinModelVersion", null)
                        .WithMany()
                        .HasForeignKey("TwinModelVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinRuntimeSession_TwinModelVersion");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinSnapshot", b =>
                {
                    b.HasOne("Nexus1.DigitalTwin.Domain.SnapshotReason", null)
                        .WithMany()
                        .HasForeignKey("SnapshotReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinSnapshot_SnapshotReason");

                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinRuntimeSession", null)
                        .WithMany()
                        .HasForeignKey("TwinRuntimeSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinSnapshot_TwinRuntimeSession");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinSnapshotValue", b =>
                {
                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinSnapshot", null)
                        .WithMany()
                        .HasForeignKey("TwinSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinSnapshotValue_TwinSnapshot");

                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinVariable", null)
                        .WithMany()
                        .HasForeignKey("TwinVariableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinSnapshotValue_TwinVariable");
                });

            modelBuilder.Entity("Nexus1.DigitalTwin.Domain.TwinVariable", b =>
                {
                    b.HasOne("Nexus1.DigitalTwin.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", null)
                        .WithMany()
                        .HasForeignKey("EngineeringUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DigitalTwin_TwinVariable_EngineeringUnit");

                    b.HasOne("Nexus1.DigitalTwin.Domain.ModelVariableType", null)
                        .WithMany()
                        .HasForeignKey("ModelVariableTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinVariable_ModelVariableType");

                    b.HasOne("Nexus1.DigitalTwin.Domain.TwinModel", null)
                        .WithMany()
                        .HasForeignKey("TwinModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DigitalTwin_TwinVariable_TwinModel");
                });
#pragma warning restore 612, 618
        }
    }
}
