// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus1.ReinforcementLearning.Infrastructure.Persistence;

#nullable disable

namespace Nexus1.ReinforcementLearning.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReinforcementLearningDbContext))]
    [Migration("20260822103225_InitialReinforcementLearningSchema")]
    partial class InitialReinforcementLearningSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.ActionDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ActionDefinitionId");

                    b.Property<int>("ActionIndex")
                        .HasColumnType("int");

                    b.Property<int>("ActionSpaceId")
                        .HasColumnType("int")
                        .HasColumnName("ActionSpaceId");

                    b.Property<decimal>("ActionValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsNoOp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_ActionDefinition");

                    b.HasIndex("ActionSpaceId", "ActionIndex")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_ActionDefinition_ActionSpace_ActionIndex");

                    b.HasIndex("ActionSpaceId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_ActionDefinition_ActionSpace_Code");

                    b.ToTable("ActionDefinition", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.ActionSpace", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ActionSpaceId");

                    b.Property<int>("ActionSpaceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ActionSpaceTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_ActionSpace");

                    b.HasIndex("ActionSpaceTypeId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_ActionSpace_Code");

                    b.HasIndex("EngineeringUnitId");

                    b.ToTable("ActionSpace", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.ActionSpaceType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ActionSpaceTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_ActionSpaceType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_ActionSpaceType_Code");

                    b.ToTable("ActionSpaceType", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.AdvisoryMode", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AdvisoryModeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_AdvisoryMode");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_AdvisoryMode_Code");

                    b.ToTable("AdvisoryMode", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.AdvisoryRecommendation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("AdvisoryRecommendationId");

                    b.Property<long>("AdvisorySessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("AdvisorySessionId");

                    b.Property<string>("ClampReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ClampedActionDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("ClampedActionDefinitionId");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(10,6)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ObservedPowerPercent")
                        .HasColumnType("decimal(12,6)");

                    b.Property<int>("RecommendationStatusId")
                        .HasColumnType("int")
                        .HasColumnName("RecommendationStatusId");

                    b.Property<int>("RecommendedActionDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("RecommendedActionDefinitionId");

                    b.Property<DateTime>("RequestedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("StateDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("StateDefinitionId");

                    b.Property<decimal?>("TargetPowerPercent")
                        .HasColumnType("decimal(12,6)");

                    b.Property<bool>("WasClamped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_AdvisoryRecommendation");

                    b.HasIndex("AdvisorySessionId");

                    b.HasIndex("ClampedActionDefinitionId");

                    b.HasIndex("RecommendationStatusId");

                    b.HasIndex("RecommendedActionDefinitionId");

                    b.HasIndex("StateDefinitionId");

                    b.ToTable("AdvisoryRecommendation", "ReinforcementLearning", t =>
                        {
                            t.HasCheckConstraint("CK_ReinforcementLearning_AdvisoryRecommendation_ConfidenceScore", "[ConfidenceScore] IS NULL OR ([ConfidenceScore] >= 0 AND [ConfidenceScore] <= 1)");
                        });
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.AdvisorySession", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("AdvisorySessionId");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PolicyDeploymentId")
                        .HasColumnType("int")
                        .HasColumnName("PolicyDeploymentId");

                    b.Property<string>("SessionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("StartedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("StartedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("StartedByUserId");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_AdvisorySession");

                    b.HasIndex("PolicyDeploymentId");

                    b.HasIndex("UnitId");

                    b.ToTable("AdvisorySession", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.EnvironmentModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("EnvironmentModelId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EnvironmentModelTypeId")
                        .HasColumnType("int")
                        .HasColumnName("EnvironmentModelTypeId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsDeterministic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RandomSeed")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TimeStepSeconds")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int?>("TwinModelId")
                        .HasColumnType("int")
                        .HasColumnName("TwinModelId");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("VersionLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_EnvironmentModel");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_EnvironmentModel_Code");

                    b.HasIndex("EnvironmentModelTypeId");

                    b.HasIndex("TwinModelId");

                    b.HasIndex("UnitId");

                    b.ToTable("EnvironmentModel", "ReinforcementLearning", t =>
                        {
                            t.HasCheckConstraint("CK_ReinforcementLearning_EnvironmentModel_TimeStepSeconds", "[TimeStepSeconds] > 0");
                        });
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.EnvironmentModelType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("EnvironmentModelTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_EnvironmentModelType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_EnvironmentModelType_Code");

                    b.ToTable("EnvironmentModelType", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ExperimentId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Objective")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerUserId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_Experiment");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_Experiment_Code");

                    b.HasIndex("UnitId");

                    b.ToTable("Experiment", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.HyperparameterSet", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("HyperparameterSetId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<decimal>("DiscountGamma")
                        .HasColumnType("decimal(10,6)");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("int");

                    b.Property<decimal>("EpsilonDecay")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("EpsilonEnd")
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("EpsilonStart")
                        .HasColumnType("decimal(10,6)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<decimal>("LearningRateAlpha")
                        .HasColumnType("decimal(10,6)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RandomSeed")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StepsPerEpisode")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_HyperparameterSet");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_HyperparameterSet_Code");

                    b.ToTable("HyperparameterSet", "ReinforcementLearning", t =>
                        {
                            t.HasCheckConstraint("CK_ReinforcementLearning_HyperparameterSet_DiscountGamma", "[DiscountGamma] >= 0 AND [DiscountGamma] <= 1");

                            t.HasCheckConstraint("CK_ReinforcementLearning_HyperparameterSet_EpisodeCount", "[EpisodeCount] > 0");

                            t.HasCheckConstraint("CK_ReinforcementLearning_HyperparameterSet_EpsilonEnd", "[EpsilonEnd] >= 0 AND [EpsilonEnd] <= 1");

                            t.HasCheckConstraint("CK_ReinforcementLearning_HyperparameterSet_EpsilonStart", "[EpsilonStart] >= 0 AND [EpsilonStart] <= 1");

                            t.HasCheckConstraint("CK_ReinforcementLearning_HyperparameterSet_LearningRateAlpha", "[LearningRateAlpha] > 0 AND [LearningRateAlpha] <= 1");

                            t.HasCheckConstraint("CK_ReinforcementLearning_HyperparameterSet_StepsPerEpisode", "[StepsPerEpisode] > 0");
                        });
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.LearningAlgorithm", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("LearningAlgorithmId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_LearningAlgorithm");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_LearningAlgorithm_Code");

                    b.ToTable("LearningAlgorithm", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.Policy", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("PolicyId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<int>("EntryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExtractedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PolicyStatusId")
                        .HasColumnType("int")
                        .HasColumnName("PolicyStatusId");

                    b.Property<int>("QTableId")
                        .HasColumnType("int")
                        .HasColumnName("QTableId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_Policy");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_Policy_Code");

                    b.HasIndex("PolicyStatusId");

                    b.HasIndex("QTableId");

                    b.ToTable("Policy", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.PolicyDeployment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("PolicyDeploymentId");

                    b.Property<int>("AdvisoryModeId")
                        .HasColumnType("int")
                        .HasColumnName("AdvisoryModeId");

                    b.Property<DateTime>("DeployedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeployedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("DeployedByUserId");

                    b.Property<string>("DeploymentNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("PolicyId");

                    b.Property<DateTime?>("RetiredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_PolicyDeployment");

                    b.HasIndex("AdvisoryModeId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UnitId");

                    b.ToTable("PolicyDeployment", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.PolicyEntry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("PolicyEntryId");

                    b.Property<decimal?>("ActionMargin")
                        .HasColumnType("decimal(20,10)");

                    b.Property<int>("BestActionDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("BestActionDefinitionId");

                    b.Property<decimal>("BestQValue")
                        .HasColumnType("decimal(20,10)");

                    b.Property<bool>("IsTie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("PolicyId");

                    b.Property<decimal?>("SecondBestQValue")
                        .HasColumnType("decimal(20,10)");

                    b.Property<int>("StateDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("StateDefinitionId");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_PolicyEntry");

                    b.HasIndex("BestActionDefinitionId");

                    b.HasIndex("StateDefinitionId");

                    b.HasIndex("PolicyId", "StateDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_PolicyEntry_Policy_StateDefinition");

                    b.ToTable("PolicyEntry", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.PolicyStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("PolicyStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_PolicyStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_PolicyStatus_Code");

                    b.ToTable("PolicyStatus", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.QTable", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("QTableId");

                    b.Property<int>("ActionSpaceId")
                        .HasColumnType("int")
                        .HasColumnName("ActionSpaceId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<int>("EntryCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("SnapshotAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("StateSpaceId")
                        .HasColumnType("int")
                        .HasColumnName("StateSpaceId");

                    b.Property<int>("TrainingRunId")
                        .HasColumnType("int")
                        .HasColumnName("TrainingRunId");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_QTable");

                    b.HasIndex("ActionSpaceId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_QTable_Code");

                    b.HasIndex("StateSpaceId");

                    b.HasIndex("TrainingRunId");

                    b.ToTable("QTable", "ReinforcementLearning", t =>
                        {
                            t.HasCheckConstraint("CK_ReinforcementLearning_QTable_EntryCount", "[EntryCount] > 0");
                        });
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.QTableEntry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("QTableEntryId");

                    b.Property<int>("ActionDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("ActionDefinitionId");

                    b.Property<DateTime?>("LastUpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("QTableId")
                        .HasColumnType("int")
                        .HasColumnName("QTableId");

                    b.Property<decimal>("QValue")
                        .HasColumnType("decimal(20,10)");

                    b.Property<int>("StateDefinitionId")
                        .HasColumnType("int")
                        .HasColumnName("StateDefinitionId");

                    b.Property<int>("VisitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_QTableEntry");

                    b.HasIndex("ActionDefinitionId");

                    b.HasIndex("StateDefinitionId");

                    b.HasIndex("QTableId", "StateDefinitionId", "ActionDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_QTableEntry_QTable_State_Action");

                    b.ToTable("QTableEntry", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.RecommendationStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RecommendationStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_RecommendationStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_RecommendationStatus_Code");

                    b.ToTable("RecommendationStatus", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.RewardFunction", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RewardFunctionId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<decimal>("ErrorWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(100.0m);

                    b.Property<string>("FormulaText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<decimal>("MovePenalty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(0.3m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RewardFunctionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RewardFunctionTypeId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_RewardFunction");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_RewardFunction_Code");

                    b.HasIndex("RewardFunctionTypeId");

                    b.ToTable("RewardFunction", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.RewardFunctionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RewardFunctionTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_RewardFunctionType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_RewardFunctionType_Code");

                    b.ToTable("RewardFunctionType", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.StateDefinition", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("StateDefinitionId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DeviationBin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsTerminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StateIndex")
                        .HasColumnType("int");

                    b.Property<int>("StateSpaceId")
                        .HasColumnType("int")
                        .HasColumnName("StateSpaceId");

                    b.Property<string>("TrendBin")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_StateDefinition");

                    b.HasIndex("StateSpaceId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_StateDefinition_StateSpace_Code");

                    b.HasIndex("StateSpaceId", "StateIndex")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_StateDefinition_StateSpace_StateIndex");

                    b.ToTable("StateDefinition", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.StateSpace", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("StateSpaceId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DimensionCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsDiscrete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StateSpaceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("StateSpaceTypeId");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_StateSpace");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_StateSpace_Code");

                    b.HasIndex("StateSpaceTypeId");

                    b.ToTable("StateSpace", "ReinforcementLearning", t =>
                        {
                            t.HasCheckConstraint("CK_ReinforcementLearning_StateSpace_DimensionCount", "[DimensionCount] > 0");
                        });
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.StateSpaceType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("StateSpaceTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_StateSpaceType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_StateSpaceType_Code");

                    b.ToTable("StateSpaceType", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.TrainingRun", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("TrainingRunId");

                    b.Property<int>("ActionSpaceId")
                        .HasColumnType("int")
                        .HasColumnName("ActionSpaceId");

                    b.Property<decimal?>("AverageReward")
                        .HasColumnType("decimal(20,6)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<int>("EnvironmentModelId")
                        .HasColumnType("int")
                        .HasColumnName("EnvironmentModelId");

                    b.Property<int>("EpisodeCountCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ExperimentId")
                        .HasColumnType("int")
                        .HasColumnName("ExperimentId");

                    b.Property<int>("HyperparameterSetId")
                        .HasColumnType("int")
                        .HasColumnName("HyperparameterSetId");

                    b.Property<int>("LearningAlgorithmId")
                        .HasColumnType("int")
                        .HasColumnName("LearningAlgorithmId");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<int>("RewardFunctionId")
                        .HasColumnType("int")
                        .HasColumnName("RewardFunctionId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("RunSeed")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("StateSpaceId")
                        .HasColumnType("int")
                        .HasColumnName("StateSpaceId");

                    b.Property<decimal?>("TotalReward")
                        .HasColumnType("decimal(20,6)");

                    b.Property<int>("TrainingRunStatusId")
                        .HasColumnType("int")
                        .HasColumnName("TrainingRunStatusId");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_TrainingRun");

                    b.HasIndex("ActionSpaceId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_TrainingRun_Code");

                    b.HasIndex("EnvironmentModelId");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("HyperparameterSetId");

                    b.HasIndex("LearningAlgorithmId");

                    b.HasIndex("RewardFunctionId");

                    b.HasIndex("StateSpaceId");

                    b.HasIndex("TrainingRunStatusId");

                    b.ToTable("TrainingRun", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.TrainingRunStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("TrainingRunStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_ReinforcementLearning_TrainingRunStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ReinforcementLearning_TrainingRunStatus_Code");

                    b.ToTable("TrainingRunStatus", "ReinforcementLearning");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", b =>
                {
                    b.Property<int>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Symbol");

                    b.HasKey("EngineeringUnitId");

                    b.ToTable("EngineeringUnit", "CorePlatform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Infrastructure.Persistence.ExternalReferences.DigitalTwinTwinModelReference", b =>
                {
                    b.Property<int>("TwinModelId")
                        .HasColumnType("int")
                        .HasColumnName("TwinModelId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Code");

                    b.HasKey("TwinModelId");

                    b.ToTable("TwinModel", "DigitalTwin", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Code");

                    b.HasKey("UnitId");

                    b.ToTable("Unit", "ReactorFleet", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.ActionDefinition", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.ActionSpace", null)
                        .WithMany()
                        .HasForeignKey("ActionSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_ActionDefinition_ActionSpace");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.ActionSpace", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.ActionSpaceType", null)
                        .WithMany()
                        .HasForeignKey("ActionSpaceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_ActionSpace_ActionSpaceType");

                    b.HasOne("Nexus1.ReinforcementLearning.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", null)
                        .WithMany()
                        .HasForeignKey("EngineeringUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RL_ActionSpace_EngineeringUnit");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.AdvisoryRecommendation", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.AdvisorySession", null)
                        .WithMany()
                        .HasForeignKey("AdvisorySessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_AdvisoryRecommendation_AdvisorySession");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.ActionDefinition", null)
                        .WithMany()
                        .HasForeignKey("ClampedActionDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RL_AdvisoryRecommendation_ClampedAction");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.RecommendationStatus", null)
                        .WithMany()
                        .HasForeignKey("RecommendationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_AdvisoryRecommendation_RecommendationStatus");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.ActionDefinition", null)
                        .WithMany()
                        .HasForeignKey("RecommendedActionDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RL_AdvisoryRecommendation_Action");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.StateDefinition", null)
                        .WithMany()
                        .HasForeignKey("StateDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_AdvisoryRecommendation_StateDefinition");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.AdvisorySession", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.PolicyDeployment", null)
                        .WithMany()
                        .HasForeignKey("PolicyDeploymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_AdvisorySession_PolicyDeployment");

                    b.HasOne("Nexus1.ReinforcementLearning.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RL_AdvisorySession_Unit");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.EnvironmentModel", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.EnvironmentModelType", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentModelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_EnvironmentModel_EnvironmentModelType");

                    b.HasOne("Nexus1.ReinforcementLearning.Infrastructure.Persistence.ExternalReferences.DigitalTwinTwinModelReference", null)
                        .WithMany()
                        .HasForeignKey("TwinModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RL_EnvironmentModel_TwinModel");

                    b.HasOne("Nexus1.ReinforcementLearning.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RL_EnvironmentModel_Unit");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.Experiment", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RL_Experiment_Unit");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.Policy", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.PolicyStatus", null)
                        .WithMany()
                        .HasForeignKey("PolicyStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_Policy_PolicyStatus");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.QTable", null)
                        .WithMany()
                        .HasForeignKey("QTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_Policy_QTable");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.PolicyDeployment", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.AdvisoryMode", null)
                        .WithMany()
                        .HasForeignKey("AdvisoryModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_PolicyDeployment_AdvisoryMode");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_PolicyDeployment_Policy");

                    b.HasOne("Nexus1.ReinforcementLearning.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RL_PolicyDeployment_Unit");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.PolicyEntry", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.ActionDefinition", null)
                        .WithMany()
                        .HasForeignKey("BestActionDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_PolicyEntry_ActionDefinition");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.Policy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_PolicyEntry_Policy");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.StateDefinition", null)
                        .WithMany()
                        .HasForeignKey("StateDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_PolicyEntry_StateDefinition");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.QTable", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.ActionSpace", null)
                        .WithMany()
                        .HasForeignKey("ActionSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_QTable_ActionSpace");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.StateSpace", null)
                        .WithMany()
                        .HasForeignKey("StateSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_QTable_StateSpace");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.TrainingRun", null)
                        .WithMany()
                        .HasForeignKey("TrainingRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_QTable_TrainingRun");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.QTableEntry", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.ActionDefinition", null)
                        .WithMany()
                        .HasForeignKey("ActionDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_QTableEntry_ActionDefinition");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.QTable", null)
                        .WithMany()
                        .HasForeignKey("QTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_QTableEntry_QTable");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.StateDefinition", null)
                        .WithMany()
                        .HasForeignKey("StateDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_QTableEntry_StateDefinition");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.RewardFunction", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.RewardFunctionType", null)
                        .WithMany()
                        .HasForeignKey("RewardFunctionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_RewardFunction_RewardFunctionType");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.StateDefinition", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.StateSpace", null)
                        .WithMany()
                        .HasForeignKey("StateSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_StateDefinition_StateSpace");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.StateSpace", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.StateSpaceType", null)
                        .WithMany()
                        .HasForeignKey("StateSpaceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_StateSpace_StateSpaceType");
                });

            modelBuilder.Entity("Nexus1.ReinforcementLearning.Domain.TrainingRun", b =>
                {
                    b.HasOne("Nexus1.ReinforcementLearning.Domain.ActionSpace", null)
                        .WithMany()
                        .HasForeignKey("ActionSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_TrainingRun_ActionSpace");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.EnvironmentModel", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_TrainingRun_EnvironmentModel");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.Experiment", null)
                        .WithMany()
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_TrainingRun_Experiment");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.HyperparameterSet", null)
                        .WithMany()
                        .HasForeignKey("HyperparameterSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_TrainingRun_HyperparameterSet");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.LearningAlgorithm", null)
                        .WithMany()
                        .HasForeignKey("LearningAlgorithmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_TrainingRun_LearningAlgorithm");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.RewardFunction", null)
                        .WithMany()
                        .HasForeignKey("RewardFunctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_TrainingRun_RewardFunction");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.StateSpace", null)
                        .WithMany()
                        .HasForeignKey("StateSpaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_TrainingRun_StateSpace");

                    b.HasOne("Nexus1.ReinforcementLearning.Domain.TrainingRunStatus", null)
                        .WithMany()
                        .HasForeignKey("TrainingRunStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ReinforcementLearning_TrainingRun_TrainingRunStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
