// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus1.ReactorFleet.Infrastructure.Persistence;

#nullable disable

namespace Nexus1.ReactorFleet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReactorFleetDbContext))]
    [Migration("20260815052328_InitialReactorFleetSchema")]
    partial class InitialReactorFleetSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus1.ReactorFleet.Domain.Unit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id")
                        .HasName("PK_ReactorFleet_Unit");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_ReactorFleet_Unit_Code");

                    b.ToTable("Unit", "ReactorFleet");
                });

            modelBuilder.Entity("Nexus1.ReactorFleet.Domain.UnitPowerSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<decimal>("PowerPercent")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("PowerPercent");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_ReactorFleet_UnitPowerSnapshot");

                    b.HasIndex("UnitId", "RecordedAtUtc")
                        .HasDatabaseName("IX_ReactorFleet_UnitPowerSnapshot_UnitId_RecordedAtUtc");

                    b.ToTable("UnitPowerSnapshot", "ReactorFleet");
                });
#pragma warning restore 612, 618
        }
    }
}
