// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus1.CorePlatform.Infrastructure.Persistence;

#nullable disable

namespace Nexus1.CorePlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CorePlatformDbContext))]
    partial class CorePlatformDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AppSettingId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_CorePlatform_AppSetting");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("UQ_CorePlatform_AppSetting_Key");

                    b.ToTable("AppSetting", "CorePlatform");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("CalendarId");

                    b.Property<string>("CalendarType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Is24x7")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TimeZoneId")
                        .HasColumnType("int")
                        .HasColumnName("TimeZoneId");

                    b.Property<TimeOnly?>("WorkingDayEnd")
                        .HasColumnType("time(0)");

                    b.Property<TimeOnly?>("WorkingDayStart")
                        .HasColumnType("time(0)");

                    b.Property<byte>("WorkingDaysMask")
                        .HasColumnType("tinyint");

                    b.HasKey("Id")
                        .HasName("PK_CorePlatform_Calendar");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_CorePlatform_Calendar_Code");

                    b.HasIndex("TimeZoneId")
                        .HasDatabaseName("IX_CorePlatform_Calendar_TimeZoneId");

                    b.ToTable("Calendar", "CorePlatform");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("CountryId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Iso2Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("Iso3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumericCode")
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("OfficialName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id")
                        .HasName("PK_CorePlatform_Country");

                    b.HasIndex("Iso2Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_CorePlatform_Country_Iso2Code");

                    b.HasIndex("Iso3Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_CorePlatform_Country_Iso3Code");

                    b.ToTable("Country", "CorePlatform");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.DeploymentVersion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("VersionId");

                    b.Property<string>("BuildSignature")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChangelogSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GitCommit")
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)")
                        .IsFixedLength();

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReleaseDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchemaMigration")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_CorePlatform_Version");

                    b.HasIndex("ComponentName")
                        .IsUnique()
                        .HasDatabaseName("UX_CorePlatform_Version_Current_Component")
                        .HasFilter("[IsCurrent] = 1");

                    b.HasIndex("ComponentName", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_CorePlatform_Version_Component_Version");

                    b.ToTable("Version", "CorePlatform");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.EngineeringUnit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDimensionless")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QuantityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SiConversionFactor")
                        .HasColumnType("decimal(28,12)");

                    b.Property<decimal?>("SiConversionOffset")
                        .HasColumnType("decimal(28,12)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_CorePlatform_EngineeringUnit");

                    b.HasIndex("QuantityType")
                        .HasDatabaseName("IX_CorePlatform_EngineeringUnit_QuantityType");

                    b.HasIndex("Symbol")
                        .IsUnique()
                        .HasDatabaseName("UQ_CorePlatform_EngineeringUnit_Symbol");

                    b.ToTable("EngineeringUnit", "CorePlatform");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.FeatureFlag", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("FeatureFlagId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EnabledFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Owner")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_CorePlatform_FeatureFlag");

                    b.HasIndex("Code", "EnvironmentName")
                        .IsUnique()
                        .HasDatabaseName("UQ_CorePlatform_FeatureFlag_Code_Environment");

                    b.ToTable("FeatureFlag", "CorePlatform");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.Language", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("LanguageId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRightToLeft")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_CorePlatform_Language");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_CorePlatform_Language_Code");

                    b.ToTable("Language", "CorePlatform");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.Localization", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("LocalizationId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMachineTranslated")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("LanguageId");

                    b.Property<DateTime?>("LastReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResourceKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SourceText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_CorePlatform_Localization");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("IX_CorePlatform_Localization_LanguageId");

                    b.HasIndex("ResourceKey")
                        .HasDatabaseName("IX_CorePlatform_Localization_ResourceKey");

                    b.HasIndex("ResourceKey", "LanguageId")
                        .IsUnique()
                        .HasDatabaseName("UQ_CorePlatform_Localization_ResourceKey_Language");

                    b.ToTable("Localization", "CorePlatform");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.Region", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RegionId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RegionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_CorePlatform_Region");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("IX_CorePlatform_Region_CountryId");

                    b.HasIndex("CountryId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_CorePlatform_Region_Country_Code");

                    b.ToTable("Region", "CorePlatform");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("SystemConfigurationId");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigurationKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_CorePlatform_SystemConfiguration");

                    b.HasIndex("ModuleName", "ConfigurationKey", "SchemaVersion")
                        .IsUnique()
                        .HasDatabaseName("UQ_CorePlatform_SystemConfiguration_Module_Key_Version");

                    b.ToTable("SystemConfiguration", "CorePlatform");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.TimeZoneReference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("TimeZoneId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<short>("CurrentUtcOffsetMinutes")
                        .HasColumnType("smallint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IanaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("ObservesDst")
                        .HasColumnType("bit");

                    b.Property<string>("WindowsName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_CorePlatform_TimeZone");

                    b.HasIndex("IanaName")
                        .IsUnique()
                        .HasDatabaseName("UQ_CorePlatform_TimeZone_IanaName");

                    b.ToTable("TimeZone", "CorePlatform");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.Calendar", b =>
                {
                    b.HasOne("Nexus1.CorePlatform.Domain.TimeZoneReference", null)
                        .WithMany()
                        .HasForeignKey("TimeZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CorePlatform_Calendar_TimeZone");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.Localization", b =>
                {
                    b.HasOne("Nexus1.CorePlatform.Domain.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CorePlatform_Localization_Language");
                });

            modelBuilder.Entity("Nexus1.CorePlatform.Domain.Region", b =>
                {
                    b.HasOne("Nexus1.CorePlatform.Domain.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CorePlatform_Region_Country");
                });
#pragma warning restore 612, 618
        }
    }
}
