<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Nexus1.ModularRuntime-422c097f-7f57-4e83-9a7f-024f60a80cb6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Contexts\ReactorFleet\Nexus1.ReactorFleet.Application\Nexus1.ReactorFleet.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\ReactorFleet\Nexus1.ReactorFleet.Infrastructure\Nexus1.ReactorFleet.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\CorePlatform\Nexus1.CorePlatform.Application\Nexus1.CorePlatform.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\CorePlatform\Nexus1.CorePlatform.Infrastructure\Nexus1.CorePlatform.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\Instrumentation\Nexus1.Instrumentation.Application\Nexus1.Instrumentation.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\Instrumentation\Nexus1.Instrumentation.Infrastructure\Nexus1.Instrumentation.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\DigitalTwin\Nexus1.DigitalTwin.Application\Nexus1.DigitalTwin.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\DigitalTwin\Nexus1.DigitalTwin.Infrastructure\Nexus1.DigitalTwin.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\Maintenance\Nexus1.Maintenance.Application\Nexus1.Maintenance.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\Maintenance\Nexus1.Maintenance.Infrastructure\Nexus1.Maintenance.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\EventManagement\Nexus1.EventManagement.Application\Nexus1.EventManagement.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\EventManagement\Nexus1.EventManagement.Infrastructure\Nexus1.EventManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\Robotics\Nexus1.Robotics.Application\Nexus1.Robotics.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\Robotics\Nexus1.Robotics.Infrastructure\Nexus1.Robotics.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\RadiationMonitoring\Nexus1.RadiationMonitoring.Application\Nexus1.RadiationMonitoring.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\RadiationMonitoring\Nexus1.RadiationMonitoring.Infrastructure\Nexus1.RadiationMonitoring.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\EmergencyPreparedness\Nexus1.EmergencyPreparedness.Application\Nexus1.EmergencyPreparedness.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\EmergencyPreparedness\Nexus1.EmergencyPreparedness.Infrastructure\Nexus1.EmergencyPreparedness.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\ReinforcementLearning\Nexus1.ReinforcementLearning.Application\Nexus1.ReinforcementLearning.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\ReinforcementLearning\Nexus1.ReinforcementLearning.Infrastructure\Nexus1.ReinforcementLearning.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\Security\Nexus1.Security.Application\Nexus1.Security.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\Security\Nexus1.Security.Infrastructure\Nexus1.Security.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\Organization\Nexus1.Organization.Application\Nexus1.Organization.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\Organization\Nexus1.Organization.Infrastructure\Nexus1.Organization.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\AlarmManagement\Nexus1.AlarmManagement.Application\Nexus1.AlarmManagement.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\AlarmManagement\Nexus1.AlarmManagement.Infrastructure\Nexus1.AlarmManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\Audit\Nexus1.Audit.Infrastructure\Nexus1.Audit.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\Compliance\Nexus1.Compliance.Infrastructure\Nexus1.Compliance.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\Reporting\Nexus1.Reporting.Infrastructure\Nexus1.Reporting.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Nexus1.BuildingBlocks.Application\Nexus1.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Nexus1.ServiceDefaults\Nexus1.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Nexus1.BuildingBlocks.Messaging\Nexus1.BuildingBlocks.Messaging.csproj" />
  </ItemGroup>

</Project>
