<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Nexus1.ModularRuntime-422c097f-7f57-4e83-9a7f-024f60a80cb6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Contexts\ReactorFleet\Nexus1.ReactorFleet.Application\Nexus1.ReactorFleet.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\ReactorFleet\Nexus1.ReactorFleet.Infrastructure\Nexus1.ReactorFleet.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\AlarmManagement\Nexus1.AlarmManagement.Application\Nexus1.AlarmManagement.Application.csproj" />
    <ProjectReference Include="..\..\Contexts\AlarmManagement\Nexus1.AlarmManagement.Infrastructure\Nexus1.AlarmManagement.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\Audit\Nexus1.Audit.Infrastructure\Nexus1.Audit.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Contexts\Compliance\Nexus1.Compliance.Infrastructure\Nexus1.Compliance.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Nexus1.BuildingBlocks.Application\Nexus1.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Nexus1.ServiceDefaults\Nexus1.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Nexus1.BuildingBlocks.Messaging\Nexus1.BuildingBlocks.Messaging.csproj" />
  </ItemGroup>

</Project>
