// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus1.RadiationMonitoring.Infrastructure.Persistence;

#nullable disable

namespace Nexus1.RadiationMonitoring.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RadiationMonitoringDbContext))]
    [Migration("20260817102432_InitialRadiationMonitoringSchema")]
    partial class InitialRadiationMonitoringSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.AlertStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("AlertStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_AlertStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_AlertStatus_Code");

                    b.ToTable("AlertStatus", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.DoseAlert", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("DoseAlertId");

                    b.Property<DateTime?>("AcknowledgedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AcknowledgedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("AcknowledgedByUserId");

                    b.Property<DateTime>("AlertAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("AlertStatusId")
                        .HasColumnType("int")
                        .HasColumnName("AlertStatusId");

                    b.Property<int>("DoseLimitId")
                        .HasColumnType("int")
                        .HasColumnName("DoseLimitId");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("PersonDoseReadingId")
                        .HasColumnType("bigint")
                        .HasColumnName("PersonDoseReadingId");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_DoseAlert");

                    b.HasIndex("AlertStatusId");

                    b.HasIndex("DoseLimitId");

                    b.HasIndex("PersonDoseReadingId");

                    b.ToTable("DoseAlert", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.DoseLimit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("DoseLimitId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<int>("DoseTypeId")
                        .HasColumnType("int")
                        .HasColumnName("DoseTypeId");

                    b.Property<int>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("LimitTypeId")
                        .HasColumnType("int")
                        .HasColumnName("LimitTypeId");

                    b.Property<decimal>("LimitValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PeriodDays")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_DoseLimit");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_DoseLimit_Code");

                    b.HasIndex("DoseTypeId");

                    b.HasIndex("EngineeringUnitId");

                    b.HasIndex("LimitTypeId");

                    b.ToTable("DoseLimit", "RadiationMonitoring", t =>
                        {
                            t.HasCheckConstraint("CK_RadiationMonitoring_DoseLimit_LimitValue", "[LimitValue] >= 0");

                            t.HasCheckConstraint("CK_RadiationMonitoring_DoseLimit_PeriodDays", "[PeriodDays] > 0");
                        });
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.DoseType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("DoseTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_DoseType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_DoseType_Code");

                    b.ToTable("DoseType", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.Dosimeter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("DosimeterId");

                    b.Property<DateTime?>("CalibrationDueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<int>("DosimeterStatusId")
                        .HasColumnType("int")
                        .HasColumnName("DosimeterStatusId");

                    b.Property<int>("DosimeterTypeId")
                        .HasColumnType("int")
                        .HasColumnName("DosimeterTypeId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_Dosimeter");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_Dosimeter_Code");

                    b.HasIndex("DosimeterStatusId");

                    b.HasIndex("DosimeterTypeId");

                    b.ToTable("Dosimeter", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.DosimeterStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("DosimeterStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_DosimeterStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_DosimeterStatus_Code");

                    b.ToTable("DosimeterStatus", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.DosimeterType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("DosimeterTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_DosimeterType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_DosimeterType_Code");

                    b.ToTable("DosimeterType", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.LimitType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("LimitTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_LimitType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_LimitType_Code");

                    b.ToTable("LimitType", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.MeasurementQuality", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("MeasurementQualityId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_MeasurementQuality");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_MeasurementQuality_Code");

                    b.ToTable("MeasurementQuality", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.MeasurementType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("MeasurementTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_MeasurementType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_MeasurementType_Code");

                    b.ToTable("MeasurementType", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.MonitorStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("MonitorStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_MonitorStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_MonitorStatus_Code");

                    b.ToTable("MonitorStatus", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.MonitorType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("MonitorTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_MonitorType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_MonitorType_Code");

                    b.ToTable("MonitorType", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.PersonDoseReading", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("PersonDoseReadingId");

                    b.Property<int>("DoseTypeId")
                        .HasColumnType("int")
                        .HasColumnName("DoseTypeId");

                    b.Property<decimal>("DoseValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<bool>("IsFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MeasurementQualityId")
                        .HasColumnType("int")
                        .HasColumnName("MeasurementQualityId");

                    b.Property<int>("PersonDosimeterAssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("PersonDosimeterAssignmentId");

                    b.Property<DateTime>("ReadingAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_PersonDoseReading");

                    b.HasIndex("DoseTypeId");

                    b.HasIndex("EngineeringUnitId");

                    b.HasIndex("MeasurementQualityId");

                    b.HasIndex("PersonDosimeterAssignmentId");

                    b.ToTable("PersonDoseReading", "RadiationMonitoring", t =>
                        {
                            t.HasCheckConstraint("CK_RadiationMonitoring_PersonDoseReading_DoseValue", "[DoseValue] >= 0");
                        });
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.PersonDosimeterAssignment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("PersonDosimeterAssignmentId");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("AssignedByUserId");

                    b.Property<string>("AssignmentPurpose")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DosimeterId")
                        .HasColumnType("int")
                        .HasColumnName("DosimeterId");

                    b.Property<int>("PersonId")
                        .HasColumnType("int")
                        .HasColumnName("PersonId");

                    b.Property<DateTime?>("ReturnedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_PersonDosimeterAssignment");

                    b.HasIndex("DosimeterId");

                    b.ToTable("PersonDosimeterAssignment", "RadiationMonitoring", t =>
                        {
                            t.HasCheckConstraint("CK_RadiationMonitoring_PersonDosimeterAssignment_ReturnedAfterAssigned", "[ReturnedAtUtc] IS NULL OR [ReturnedAtUtc] > [AssignedAtUtc]");
                        });
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.RadiationAreaClassification", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RadiationAreaClassificationId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_RadiationAreaClassification");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_RadiationAreaClassification_Code");

                    b.ToTable("RadiationAreaClassification", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.RadiationMonitor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RadiationMonitorId");

                    b.Property<DateTime?>("CalibrationDueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentId");

                    b.Property<DateTime?>("InstalledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<int>("MonitorStatusId")
                        .HasColumnType("int")
                        .HasColumnName("MonitorStatusId");

                    b.Property<int>("MonitorTypeId")
                        .HasColumnType("int")
                        .HasColumnName("MonitorTypeId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RadiationZoneId")
                        .HasColumnType("int")
                        .HasColumnName("RadiationZoneId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_RadiationMonitor");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_RadiationMonitor_Code");

                    b.HasIndex("MonitorStatusId");

                    b.HasIndex("MonitorTypeId");

                    b.HasIndex("RadiationZoneId");

                    b.HasIndex("UnitId");

                    b.ToTable("RadiationMonitor", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.RadiationReading", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("RadiationReadingId");

                    b.Property<int>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<bool>("IsAlarmRelevant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MeasurementQualityId")
                        .HasColumnType("int")
                        .HasColumnName("MeasurementQualityId");

                    b.Property<int>("MeasurementTypeId")
                        .HasColumnType("int")
                        .HasColumnName("MeasurementTypeId");

                    b.Property<int>("RadiationMonitorId")
                        .HasColumnType("int")
                        .HasColumnName("RadiationMonitorId");

                    b.Property<DateTime?>("SourceTimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_RadiationReading");

                    b.HasIndex("EngineeringUnitId");

                    b.HasIndex("MeasurementQualityId");

                    b.HasIndex("MeasurementTypeId");

                    b.HasIndex("RadiationMonitorId");

                    b.ToTable("RadiationReading", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.RadiationZone", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RadiationZoneId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EquipmentLocationId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentLocationId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsEntryControlled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("PostedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RadiationAreaClassificationId")
                        .HasColumnType("int")
                        .HasColumnName("RadiationAreaClassificationId");

                    b.Property<int>("RadiationZoneStatusId")
                        .HasColumnType("int")
                        .HasColumnName("RadiationZoneStatusId");

                    b.Property<int>("RadiationZoneTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RadiationZoneTypeId");

                    b.Property<bool>("RequiresDosimeter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_RadiationZone");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_RadiationZone_Code");

                    b.HasIndex("RadiationAreaClassificationId");

                    b.HasIndex("RadiationZoneStatusId");

                    b.HasIndex("RadiationZoneTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("RadiationZone", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.RadiationZoneStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RadiationZoneStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_RadiationZoneStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_RadiationZoneStatus_Code");

                    b.ToTable("RadiationZoneStatus", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.RadiationZoneType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RadiationZoneTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_RadiationMonitoring_RadiationZoneType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_RadiationMonitoring_RadiationZoneType_Code");

                    b.ToTable("RadiationZoneType", "RadiationMonitoring");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", b =>
                {
                    b.Property<int>("EngineeringUnitId")
                        .HasColumnType("int")
                        .HasColumnName("EngineeringUnitId");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Symbol");

                    b.HasKey("EngineeringUnitId");

                    b.ToTable("EngineeringUnit", "CorePlatform", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Code");

                    b.HasKey("UnitId");

                    b.ToTable("Unit", "ReactorFleet", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.DoseAlert", b =>
                {
                    b.HasOne("Nexus1.RadiationMonitoring.Domain.AlertStatus", null)
                        .WithMany()
                        .HasForeignKey("AlertStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_DoseAlert_AlertStatus");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.DoseLimit", null)
                        .WithMany()
                        .HasForeignKey("DoseLimitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_DoseAlert_DoseLimit");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.PersonDoseReading", null)
                        .WithMany()
                        .HasForeignKey("PersonDoseReadingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RadiationMonitoring_DoseAlert_PersonDoseReading");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.DoseLimit", b =>
                {
                    b.HasOne("Nexus1.RadiationMonitoring.Domain.DoseType", null)
                        .WithMany()
                        .HasForeignKey("DoseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_DoseLimit_DoseType");

                    b.HasOne("Nexus1.RadiationMonitoring.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", null)
                        .WithMany()
                        .HasForeignKey("EngineeringUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DoseLimit_EngineeringUnit");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.LimitType", null)
                        .WithMany()
                        .HasForeignKey("LimitTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_DoseLimit_LimitType");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.Dosimeter", b =>
                {
                    b.HasOne("Nexus1.RadiationMonitoring.Domain.DosimeterStatus", null)
                        .WithMany()
                        .HasForeignKey("DosimeterStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_Dosimeter_DosimeterStatus");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.DosimeterType", null)
                        .WithMany()
                        .HasForeignKey("DosimeterTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_Dosimeter_DosimeterType");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.PersonDoseReading", b =>
                {
                    b.HasOne("Nexus1.RadiationMonitoring.Domain.DoseType", null)
                        .WithMany()
                        .HasForeignKey("DoseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_PersonDoseReading_DoseType");

                    b.HasOne("Nexus1.RadiationMonitoring.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", null)
                        .WithMany()
                        .HasForeignKey("EngineeringUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PersonDoseReading_EngineeringUnit");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.MeasurementQuality", null)
                        .WithMany()
                        .HasForeignKey("MeasurementQualityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_PersonDoseReading_MeasurementQuality");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.PersonDosimeterAssignment", null)
                        .WithMany()
                        .HasForeignKey("PersonDosimeterAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_PersonDoseReading_PersonDosimeterAssignment");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.PersonDosimeterAssignment", b =>
                {
                    b.HasOne("Nexus1.RadiationMonitoring.Domain.Dosimeter", null)
                        .WithMany()
                        .HasForeignKey("DosimeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_PersonDosimeterAssignment_Dosimeter");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.RadiationMonitor", b =>
                {
                    b.HasOne("Nexus1.RadiationMonitoring.Domain.MonitorStatus", null)
                        .WithMany()
                        .HasForeignKey("MonitorStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_RadiationMonitor_MonitorStatus");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.MonitorType", null)
                        .WithMany()
                        .HasForeignKey("MonitorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_RadiationMonitor_MonitorType");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.RadiationZone", null)
                        .WithMany()
                        .HasForeignKey("RadiationZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RadiationMonitoring_RadiationMonitor_RadiationZone");

                    b.HasOne("Nexus1.RadiationMonitoring.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RadiationMonitor_Unit");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.RadiationReading", b =>
                {
                    b.HasOne("Nexus1.RadiationMonitoring.Infrastructure.Persistence.ExternalReferences.CorePlatformEngineeringUnitReference", null)
                        .WithMany()
                        .HasForeignKey("EngineeringUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationReading_EngineeringUnit");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.MeasurementQuality", null)
                        .WithMany()
                        .HasForeignKey("MeasurementQualityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_RadiationReading_MeasurementQuality");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.MeasurementType", null)
                        .WithMany()
                        .HasForeignKey("MeasurementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_RadiationReading_MeasurementType");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.RadiationMonitor", null)
                        .WithMany()
                        .HasForeignKey("RadiationMonitorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_RadiationReading_RadiationMonitor");
                });

            modelBuilder.Entity("Nexus1.RadiationMonitoring.Domain.RadiationZone", b =>
                {
                    b.HasOne("Nexus1.RadiationMonitoring.Domain.RadiationAreaClassification", null)
                        .WithMany()
                        .HasForeignKey("RadiationAreaClassificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_RadiationZone_RadiationAreaClassification");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.RadiationZoneStatus", null)
                        .WithMany()
                        .HasForeignKey("RadiationZoneStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_RadiationZone_RadiationZoneStatus");

                    b.HasOne("Nexus1.RadiationMonitoring.Domain.RadiationZoneType", null)
                        .WithMany()
                        .HasForeignKey("RadiationZoneTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RadiationMonitoring_RadiationZone_RadiationZoneType");

                    b.HasOne("Nexus1.RadiationMonitoring.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_RadiationZone_Unit");
                });
#pragma warning restore 612, 618
        }
    }
}
