<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Contexts\Maintenance\Nexus1.Maintenance.Infrastructure\Nexus1.Maintenance.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Contexts\Maintenance\Nexus1.Maintenance.Application\Nexus1.Maintenance.Application.csproj" />
    <ProjectReference Include="..\..\src\Contexts\ReactorFleet\Nexus1.ReactorFleet.Infrastructure\Nexus1.ReactorFleet.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Contexts\CorePlatform\Nexus1.CorePlatform.Infrastructure\Nexus1.CorePlatform.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Contexts\Instrumentation\Nexus1.Instrumentation.Infrastructure\Nexus1.Instrumentation.Infrastructure.csproj" />
  </ItemGroup>

</Project>
