// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus1.EventManagement.Infrastructure.Persistence;

#nullable disable

namespace Nexus1.EventManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EventManagementDbContext))]
    partial class EventManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus1.EventManagement.Domain.EventAlarmLink", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("EventAlarmLinkId");

                    b.Property<long>("AlarmEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("AlarmEventId");

                    b.Property<string>("LinkRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("OperationalEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("OperationalEventId");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_EventAlarmLink");

                    b.HasIndex("AlarmEventId");

                    b.HasIndex("OperationalEventId", "AlarmEventId")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_EventAlarmLink");

                    b.ToTable("EventAlarmLink", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.EventFloodLink", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("EventFloodLinkId");

                    b.Property<long>("AlarmFloodId")
                        .HasColumnType("bigint")
                        .HasColumnName("AlarmFloodId");

                    b.Property<string>("LinkRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("OperationalEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("OperationalEventId");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_EventFloodLink");

                    b.HasIndex("AlarmFloodId");

                    b.HasIndex("OperationalEventId", "AlarmFloodId")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_EventFloodLink");

                    b.ToTable("EventFloodLink", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.EventSeverity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("EventSeverityId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_EventSeverity");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_EventSeverity_Code");

                    b.ToTable("EventSeverity", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.EventSourceType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("EventSourceTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_EventSourceType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_EventSourceType_Code");

                    b.ToTable("EventSourceType", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.EventStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("EventStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_EventStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_EventStatus_Code");

                    b.ToTable("EventStatus", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.EventTimelineEntry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("EventTimelineEntryId");

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("EnteredByUserId")
                        .HasColumnType("int")
                        .HasColumnName("EnteredByUserId");

                    b.Property<DateTime>("EntryAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventTimelineEntryTypeId")
                        .HasColumnType("int")
                        .HasColumnName("EventTimelineEntryTypeId");

                    b.Property<long>("OperationalEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("OperationalEventId");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_EventTimelineEntry");

                    b.HasIndex("EventTimelineEntryTypeId");

                    b.HasIndex("OperationalEventId");

                    b.ToTable("EventTimelineEntry", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.EventTimelineEntryType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("EventTimelineEntryTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_EventTimelineEntryType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_EventTimelineEntryType_Code");

                    b.ToTable("EventTimelineEntryType", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.EventType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("EventTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_EventType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_EventType_Code");

                    b.ToTable("EventType", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.Incident", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("IncidentId");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("IncidentNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("IncidentStatusId")
                        .HasColumnType("int")
                        .HasColumnName("IncidentStatusId");

                    b.Property<int>("IncidentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("IncidentTypeId");

                    b.Property<string>("InvestigationSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("LeadInvestigatorUserId")
                        .HasColumnType("int")
                        .HasColumnName("LeadInvestigatorUserId");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("OpenedAtUtc");

                    b.Property<long>("OperationalEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("OperationalEventId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_Incident");

                    b.HasIndex("IncidentNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_Incident_IncidentNumber");

                    b.HasIndex("IncidentStatusId");

                    b.HasIndex("IncidentTypeId");

                    b.HasIndex("OperationalEventId")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_Incident_OperationalEvent");

                    b.ToTable("Incident", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.IncidentAction", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("IncidentActionId");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidentActionStatusId")
                        .HasColumnType("int")
                        .HasColumnName("IncidentActionStatusId");

                    b.Property<int>("IncidentActionTypeId")
                        .HasColumnType("int")
                        .HasColumnName("IncidentActionTypeId");

                    b.Property<long>("IncidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("IncidentId");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("VerifiedByUserId");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_IncidentAction");

                    b.HasIndex("IncidentActionStatusId");

                    b.HasIndex("IncidentActionTypeId");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentAction", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.IncidentActionStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("IncidentActionStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_IncidentActionStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_IncidentActionStatus_Code");

                    b.ToTable("IncidentActionStatus", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.IncidentActionType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("IncidentActionTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_IncidentActionType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_IncidentActionType_Code");

                    b.ToTable("IncidentActionType", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.IncidentStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("IncidentStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_IncidentStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_IncidentStatus_Code");

                    b.ToTable("IncidentStatus", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.IncidentType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("IncidentTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_IncidentType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_IncidentType_Code");

                    b.ToTable("IncidentType", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.OperationalEvent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("OperationalEventId");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("EventSeverityId")
                        .HasColumnType("int")
                        .HasColumnName("EventSeverityId");

                    b.Property<int>("EventSourceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("EventSourceTypeId");

                    b.Property<int>("EventStatusId")
                        .HasColumnType("int")
                        .HasColumnName("EventStatusId");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int")
                        .HasColumnName("EventTypeId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsDrill")
                        .HasColumnType("bit")
                        .HasColumnName("IsDrill");

                    b.Property<DateTime>("ModifiedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ModifiedAtUtc")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ModifiedBy")
                        .HasDefaultValueSql("N'system'");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerUserId");

                    b.Property<int?>("OwningPersonId")
                        .HasColumnType("int")
                        .HasColumnName("OwningPersonId");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int")
                        .HasColumnName("PlantId");

                    b.Property<DateTime>("ReportedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ReportedAtUtc");

                    b.Property<int?>("ReportedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("ReportedByUserId");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.HasKey("Id")
                        .HasName("PK_EventManagement_OperationalEvent");

                    b.HasIndex("EventCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_EventManagement_OperationalEvent_EventCode");

                    b.HasIndex("EventSeverityId");

                    b.HasIndex("EventSourceTypeId");

                    b.HasIndex("EventStatusId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("UnitId");

                    b.ToTable("OperationalEvent", "EventManagement");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Infrastructure.Persistence.ExternalReferences.AlarmManagementAlarmEventReference", b =>
                {
                    b.Property<long>("AlarmEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("AlarmEventId");

                    b.HasKey("AlarmEventId");

                    b.ToTable("AlarmEvent", "AlarmManagement", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.EventManagement.Infrastructure.Persistence.ExternalReferences.AlarmManagementAlarmFloodReference", b =>
                {
                    b.Property<long>("AlarmFloodId")
                        .HasColumnType("bigint")
                        .HasColumnName("AlarmFloodId");

                    b.HasKey("AlarmFloodId");

                    b.ToTable("AlarmFlood", "AlarmManagement", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.EventManagement.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", b =>
                {
                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Code");

                    b.HasKey("UnitId");

                    b.ToTable("Unit", "ReactorFleet", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.EventAlarmLink", b =>
                {
                    b.HasOne("Nexus1.EventManagement.Infrastructure.Persistence.ExternalReferences.AlarmManagementAlarmEventReference", null)
                        .WithMany()
                        .HasForeignKey("AlarmEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_EventAlarmLink_AlarmEvent");

                    b.HasOne("Nexus1.EventManagement.Domain.OperationalEvent", null)
                        .WithMany()
                        .HasForeignKey("OperationalEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_EventAlarmLink_OperationalEvent");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.EventFloodLink", b =>
                {
                    b.HasOne("Nexus1.EventManagement.Infrastructure.Persistence.ExternalReferences.AlarmManagementAlarmFloodReference", null)
                        .WithMany()
                        .HasForeignKey("AlarmFloodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_EventFloodLink_AlarmFlood");

                    b.HasOne("Nexus1.EventManagement.Domain.OperationalEvent", null)
                        .WithMany()
                        .HasForeignKey("OperationalEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_EventFloodLink_OperationalEvent");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.EventTimelineEntry", b =>
                {
                    b.HasOne("Nexus1.EventManagement.Domain.EventTimelineEntryType", null)
                        .WithMany()
                        .HasForeignKey("EventTimelineEntryTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_EventTimelineEntry_Type");

                    b.HasOne("Nexus1.EventManagement.Domain.OperationalEvent", null)
                        .WithMany()
                        .HasForeignKey("OperationalEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_EventTimelineEntry_OperationalEvent");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.Incident", b =>
                {
                    b.HasOne("Nexus1.EventManagement.Domain.IncidentStatus", null)
                        .WithMany()
                        .HasForeignKey("IncidentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_Incident_IncidentStatus");

                    b.HasOne("Nexus1.EventManagement.Domain.IncidentType", null)
                        .WithMany()
                        .HasForeignKey("IncidentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_Incident_IncidentType");

                    b.HasOne("Nexus1.EventManagement.Domain.OperationalEvent", null)
                        .WithMany()
                        .HasForeignKey("OperationalEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_Incident_OperationalEvent");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.IncidentAction", b =>
                {
                    b.HasOne("Nexus1.EventManagement.Domain.IncidentActionStatus", null)
                        .WithMany()
                        .HasForeignKey("IncidentActionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_IncidentAction_Status");

                    b.HasOne("Nexus1.EventManagement.Domain.IncidentActionType", null)
                        .WithMany()
                        .HasForeignKey("IncidentActionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_IncidentAction_Type");

                    b.HasOne("Nexus1.EventManagement.Domain.Incident", null)
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_IncidentAction_Incident");
                });

            modelBuilder.Entity("Nexus1.EventManagement.Domain.OperationalEvent", b =>
                {
                    b.HasOne("Nexus1.EventManagement.Domain.EventSeverity", null)
                        .WithMany()
                        .HasForeignKey("EventSeverityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_OperationalEvent_EventSeverity");

                    b.HasOne("Nexus1.EventManagement.Domain.EventSourceType", null)
                        .WithMany()
                        .HasForeignKey("EventSourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_OperationalEvent_EventSourceType");

                    b.HasOne("Nexus1.EventManagement.Domain.EventStatus", null)
                        .WithMany()
                        .HasForeignKey("EventStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_OperationalEvent_EventStatus");

                    b.HasOne("Nexus1.EventManagement.Domain.EventType", null)
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_OperationalEvent_EventType");

                    b.HasOne("Nexus1.EventManagement.Infrastructure.Persistence.ExternalReferences.ReactorFleetUnitReference", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventManagement_OperationalEvent_Unit");
                });
#pragma warning restore 612, 618
        }
    }
}
