// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus1.Security.Infrastructure.Persistence;

#nullable disable

namespace Nexus1.Security.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SecurityDbContext))]
    [Migration("20260816124526_InitialSecuritySchema")]
    partial class InitialSecuritySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus1.Security.Domain.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationRoleId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("ParentRoleId")
                        .HasColumnType("int")
                        .HasColumnName("ParentRoleId");

                    b.Property<int>("RoleTypeId")
                        .HasColumnType("int")
                        .HasColumnName("RoleTypeId");

                    b.HasKey("Id")
                        .HasName("PK_Security_ApplicationRole");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Security_ApplicationRole_NormalizedName");

                    b.HasIndex("ParentRoleId");

                    b.HasIndex("RoleTypeId");

                    b.ToTable("ApplicationRole", "Security");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationUserId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FamilyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GivenName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsServiceAccount")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserStatusId")
                        .HasColumnType("int")
                        .HasColumnName("UserStatusId");

                    b.HasKey("Id")
                        .HasName("PK_Security_ApplicationUser");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Security_ApplicationUser_NormalizedUserName");

                    b.HasIndex("UserStatusId");

                    b.ToTable("ApplicationUser", "Security", t =>
                        {
                            t.HasCheckConstraint("CK_Security_ApplicationUser_AccessFailedCount", "[AccessFailedCount] >= 0");
                        });
                });

            modelBuilder.Entity("Nexus1.Security.Domain.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSafetyRelevant")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("PermissionCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionCategoryId");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id")
                        .HasName("PK_Security_Permission");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Security_Permission_Code");

                    b.HasIndex("PermissionCategoryId");

                    b.ToTable("Permission", "Security");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.PermissionCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("PermissionCategoryId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Security_PermissionCategory");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Security_PermissionCategory_Code");

                    b.ToTable("PermissionCategory", "Security");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.RolePermission", b =>
                {
                    b.Property<int>("ApplicationRoleId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationRoleId");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("PermissionId");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GrantedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GrantedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("GrantedByUserId");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.HasKey("ApplicationRoleId", "PermissionId")
                        .HasName("PK_Security_RolePermission");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", "Security");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.RoleType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("RoleTypeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Security_RoleType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Security_RoleType_Code");

                    b.ToTable("RoleType", "Security");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationUserId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateFormat")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("LanguageId");

                    b.Property<string>("NumberFormat")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("ReceiveEmailAlerts")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceiveInAppAlerts")
                        .HasColumnType("bit");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TimeZoneId")
                        .HasColumnType("int")
                        .HasColumnName("TimeZoneId");

                    b.HasKey("Id")
                        .HasName("PK_Security_UserPreference");

                    b.ToTable("UserPreference", "Security");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.UserRole", b =>
                {
                    b.Property<int>("ApplicationUserId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationUserId");

                    b.Property<int>("ApplicationRoleId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationRoleId");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("AssignedByUserId");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ApplicationUserId", "ApplicationRoleId")
                        .HasName("PK_Security_UserRole");

                    b.HasIndex("ApplicationRoleId");

                    b.HasIndex("AssignedByUserId");

                    b.ToTable("UserRole", "Security");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("UserStatusId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Security_UserStatus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Security_UserStatus_Code");

                    b.ToTable("UserStatus", "Security");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.ApplicationRole", b =>
                {
                    b.HasOne("Nexus1.Security.Domain.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("ParentRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Security_ApplicationRole_ParentRole");

                    b.HasOne("Nexus1.Security.Domain.RoleType", null)
                        .WithMany()
                        .HasForeignKey("RoleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Security_ApplicationRole_RoleType");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.ApplicationUser", b =>
                {
                    b.HasOne("Nexus1.Security.Domain.UserStatus", null)
                        .WithMany()
                        .HasForeignKey("UserStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Security_ApplicationUser_UserStatus");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.Permission", b =>
                {
                    b.HasOne("Nexus1.Security.Domain.PermissionCategory", null)
                        .WithMany()
                        .HasForeignKey("PermissionCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Security_Permission_PermissionCategory");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.RolePermission", b =>
                {
                    b.HasOne("Nexus1.Security.Domain.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Security_RolePermission_ApplicationRole");

                    b.HasOne("Nexus1.Security.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Security_RolePermission_GrantedByUser");

                    b.HasOne("Nexus1.Security.Domain.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Security_RolePermission_Permission");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.UserPreference", b =>
                {
                    b.HasOne("Nexus1.Security.Domain.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Nexus1.Security.Domain.UserPreference", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Security_UserPreference_ApplicationUser");
                });

            modelBuilder.Entity("Nexus1.Security.Domain.UserRole", b =>
                {
                    b.HasOne("Nexus1.Security.Domain.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("ApplicationRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Security_UserRole_ApplicationRole");

                    b.HasOne("Nexus1.Security.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Security_UserRole_ApplicationUser");

                    b.HasOne("Nexus1.Security.Domain.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Security_UserRole_AssignedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
